### ISSUE TITLE
Imports in Pyjnius that may be Hidden from Pyinstaller

### ISSUE THREAD

**Issue by evbo** [kivy/pyjnius#116]
In order to produce an executable using Pyinstaller I need to make sure all Pyjnius dependent modules/jars/dlls are explicitly imported for Pyinstaller to bundle them.

I've tried searching for the missing dependencies by skimming through the Pyjnius source code but can't seem to locate any import statements that might otherwise be hidden from Pyinstaller (since it only sees the jnius.pyd file).

Any idea what imports might be hidden from Pyinstaller (for instance Cython, NativeInvocationHandler.jar, etc.)?

The reason why I am assuming an import is hidden from pyinstaller is because it is throwing an error that there are missing DLLs when it tries to load jnius.jnius.pyd:

```
File "C:\python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\loader\pyi_importers.py", line 409, in load_module
ImportError: DLL load failed: The specified module could not be found.
```
##

**Comment by MarkTillotson** [comment]
Have a similar issue with other modules - very impolite of the error report not mentioning the name of the offending module I feel...

**Comment by evbo** [comment]
I think this answers the question: https://github.com/kivy/pyjnius/pull/373/commits/2ff175f0fc8e3fa2e62ef2cc729803f3d6067ccd
