### ISSUE TITLE
Segmentation fault occurs in wrapped C lib, only when jnius is imported

### ISSUE THREAD

**Issue by kgori** [kivy/pyjnius#136]
I have a C library that I have wrapped with a C++ class, and cython. I get a segmentation fault when running one of the C functions, but only if I have imported jnius. If I don't import jnius the function returns just fine. Any idea what might be going on?

The C lib is [libpll](https://www.assembla.com/code/phylogenetic-likelihood-library/git/nodes/)
the wrapper is [here](https://pypi.python.org/pypi/pllpy/0.1.10)
I'm using Red Hat Enterprise Linux Server release 6.3 (Santiago) kernel version 2.6.32-358.14.1.el6.x86_64

**Comment by tito** [comment]
Maybe did you compiled both with a different libc, or something else? Theses kind of crash might came from different compilation settings or env. If you post a full gdb backtrace, we might be able to help, but at this point, there is nothing else we can do. Sorry :/
