### ISSUE TITLE
Use appveyor.com to run tests on Windows

### ISSUE THREAD

**Issue by luzfcb** [kivy/pyjnius#145]
I tried to install in every way the pyjnius on Windows 7, and I'm having this error:
https://gist.github.com/luzfcb/620c5811d2bffadfbe2d

My installation of Python 2.7 is perfect and correct (I use [Python (x, y)](https://code.google.com/p/pythonxy/) because it already contains all the libraries I need and compiler C / C ++ )

I want to use pyjnius without depending on Kivy. 

I think it would be good to use the CI server to test against Windows.
Currently, the only option I know who works in a similar way that Travis is the [Appveyor](http://www.appveyor.com)

The Appveyor standard VM seems that already has all the necessary tools to compile pyjnius:

http://www.appveyor.com/docs/installed-software
http://www.appveyor.com/docs

A good example of Python library that uses the Appveyor as CI is the [Cookiecutter](https://github.com/audreyr/cookiecutter)

https://github.com/audreyr/cookiecutter/tree/master/appveyor
https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml
https://github.com/audreyr/cookiecutter/blob/master/tox.ini
##

**Comment by KeyWeeUsr** [comment]
Closed by #370.
