### ISSUE TITLE
Memory leak when passing arrays of strings as methods' arguments

### ISSUE THREAD

**Issue by fabiofabris** [kivy/pyjnius#155]
Hello all.

I've been experience some "out of memory" errors when using pyjnius, specially when passing arrays of strings to methods. Here is an example:

Consider this sample python file:

``` python
import sys
import jnius_config
jnius_config.add_options('-Xms100M', '-Xmx100M')

from jnius import autoclass

TestFactory = autoclass('test.Test')
test = TestFactory()

for c in xrange(int(sys.argv[1])):
    arg = ["some string" for _ in xrange(1000)]
    test.test(arg)
    print "counter:", c
```

And the corresponding java implementation:

``` java
package test;

public class Test{
    public void test(String[] arg){}
    public void test_noarg(){}
}
```

What I've been experiencing is that after around 1600 test.test(arg) calls, the process struggles with memory, eventually crashing. This does not happen if one substitutes test.test(arg) for test.test_noarg(), what points to a problem in the handling of String arrays arguments. In fact, valgrind --leak-check=full reports that several bytes are lost at line 538 of jnius_conversion.pxi ( j_string = j_env[0].NewStringUTF(j_env, <bytes>arg)).

And if I comment-out lines 538 to 542, the problem disappears. 

``` python
                # j_string = j_env[0].NewStringUTF(
                #         j_env, arg)
                #
                # j_env[0].SetObjectArrayElement(
                #         j_env, <jobjectArray>ret, i, j_string)
```

I'm using pyjnius version 1.1-dev, Cython-0.22, java version "1.7.0_25", python version 2.7.4 under Linux Mint 15.
##

**Comment by alex457** [comment]
The issue still exits, [this issue](https://github.com/kivy/pyjnius/issues/170) seems to be relevant for the bug.
