### ISSUE TITLE
Can't make an EnumMap?

### ISSUE THREAD

**Issue by benson-basis** [kivy/pyjnius#159]
```
EnumMap = autoclass('java.util.EnumMap')
SomeEnum = autoclass('my.enum.class')
map = EnumMap(SomeEnum)

fails due to a lack of a suitable ctor.

**Comment by kived** [comment]
Try accessing the property from the autoclass itself, i.e.:

    SomeEnum = autoclass('my.enum')
    map = EnumMap(SomeEnum.class)

**Comment by benson-basis** [comment]
That's invalid python syntax. You can't write '.class' on the end of it. Maybe .__javaclass__ would work.
