### ISSUE TITLE
beans and lists

### ISSUE THREAD

**Issue by benson-basis** [kivy/pyjnius#161]
I have coded some additions to autoclass in reflect.py so that:
-  getX() and isX() method cause an \@property to be added that returns the value.
- An object that implements java.util.List gets __getitem__ and __len__.

Is there a committer interested in this? How could I make it optional, given that it's maximally useful for the classes that come into existence for returned objects?

I'm not so interested in the 'write' side of this idea, but I could perhaps be persuaded to go there.
##

**Comment by Julian-O** [comment]
Thanks for the offer, but after 8 years and no interest, I am going to call this.

Closing as Stale.
