### ISSUE TITLE
can't import Contacts

### ISSUE THREAD

**Issue by Hukuta** [kivy/pyjnius#180]
This code crashes without catching Exception:

    def build(self):
        try:
            return Label(text=str(dir(autoclass('android.provider.ContactsContract.Contacts'))).replace(' ', '\n'))
        except Exception as ex:
            return Label(text=str(ex).replace(' ', '\n'))

this case 

    def build(self):
        try:
            contract = autoclass('android.provider.ContactsContract')
            return Label(text=str(dir(contract.Contacts)).replace(' ', '\n'))
        except Exception as ex:
            return Label(text=str(ex).replace(' ', '\n')) 

catching Exception **type object 'android.provider.ContactsContract' has no attribute 'Contacts'**

but I expect that such a class exists: http://developer.android.com/intl/ru/reference/android/provider/ContactsContract.Contacts.html

**Comment by pythonic64** [comment]
Try importing Contacts directly, like:
```
Contacts = autoclass('android.provider.ContactsContract$Contacts')
```

**Comment by Hukuta** [comment]
it works, thanks!

**Comment by Hukuta** [comment]
One more question.
How to get "ContactsContract.Contacts._ID" ?

    Contacts = autoclass('android.provider.ContactsContract$Contacts')
    System.out.println(' '.join(dir(Contacts))) # CONTACT_CHAT_CAPABILITY CONTACT_LAST_UPDATED_TIMESTAMP CONTACT_PRESENCE CONTACT_STATUS CONTACT_STATUS_ICON CONTACT_STATUS_LABEL CONTACT_STATUS_RES_PACKAGE CONTACT_STATUS_TIMESTAMP CONTENT_FILTER_URI CONTENT_FREQUENT_URI CONTENT_GROUP_URI CONTENT_ITEM_TYPE CONTENT_LOOKUP_URI CONTENT_MULTI_VCARD_URI CONTENT_STREQUENT_FILTER_URI CONTENT_STREQUENT_URI CONTENT_TYPE CONTENT_URI CONTENT_VCARD_TYPE CONTENT_VCARD_URI CORP_CONTENT_URI CUSTOM_RINGTONE DISPLAY_NAME DISPLAY_NAME_ALTERNATIVE DISPLAY_NAME_PRIMARY DISPLAY_NAME_SOURCE ENTERPRISE_CONTACT_ID_BASE EXTRA_ADDRESS_BOOK_INDEX EXTRA_ADDRESS_BOOK_INDEX_COUNTS EXTRA_ADDRESS_BOOK_INDEX_TITLES FILTER FILTER_NONE FILTER_WIDGET HAS_PHONE_NUMBER INDEX_IN_SIM INDICATE_PHONE_SIM IN_DEFAULT_DIRECTORY IN_VISIBLE_GROUP IS_SDN_CONTACT IS_USER_PROFILE LAST_TIME_CONTACTED LOOKUP_KEY NAME_RAW_CONTACT_ID PHONETIC_NAME PHONETIC_NAME_STYLE PHOTO_FILE_ID PHOTO_ID PHOTO_THUMBNAIL_URI PHOTO_URI PINNED QUERY_PARAMETER_VCARD_NO_PHOTO SEND_TO_VOICEMAIL SEND_TO_VOICEMAIL_SIP SEND_TO_VOICEMAIL_VT SORT_KEY_ALTERNATIVE SORT_KEY_PRIMARY STARRED TIMES_CONTACTED _COUNT _ID
    _ID = Contacts._ID # Error

**Comment by pythonic64** [comment]
That's an issue with pyjinius related to https://github.com/kivy/pyjnius/issues/169
You'll have declare variable yourself, like:
'''
CONTACTS_ID = '_id'
'''
and then instead of using Contacts._ID use CONTACTS_ID when building query for accessing Contacts.

**Comment by Intasir** [comment]
how can i Access full contact list ,can anyone help??
