### ISSUE TITLE
Cannot import name

### ISSUE THREAD

**Issue by pebbie** [kivy/pyjnius#182]
JavaStaticField, JavaStaticMethod, JavaMultipleMethod

I'm using Python 3.5_amd64, Visual Studio 2015 and JDK 1.8.0 (64bit). the module compiles after some small hack (lib dir) but when i tried to import it cannot import names above. any hints on how to solve this?
##

**Comment by Arnie97** [comment]
See #327.

**Comment by tshirtman** [comment]
closing as duplicate
