### ISSUE TITLE
Request for PyPi release

### ISSUE THREAD

**Issue by blootsvoets** [kivy/pyjnius#189]
The 1.0.2 version does not install on OS X and seems to give problems with Python 3. Version 1.1 solves that but is not released to PyPi. Could a release be made for 1.1? Are there issues are preventing the release?
##

**Comment by inclement** [comment]
@tito Could you do this?

**Comment by tito** [comment]
Going to

**Comment by blootsvoets** [comment]
Small reminder, we would really like to have a working release on PyPi, so Mac and Python 3 works on the official release.

**Comment by blootsvoets** [comment]
Is this blocked by a specific issue or pull request? Is there something I could do to facilitate this?

**Comment by kived** [comment]
FYI, you can install straight from GitHub, and for the most common use case (Android) we always use master anyway. `pip install https://github.com/kivy/pyjnius/archive/master.zip`

@tito @dessant @matham Are we ready to push a new release? You three are the guys with access. ;)

**Comment by dessant** [comment]
@kived, we can make you the fourth. :grin:

**Comment by dessant** [comment]
We have reserved the package name: https://pypi.python.org/pypi/pyjnius.
https://pypi.python.org/pypi/jnius will be eventually deleted.

**Comment by ngoonee** [comment]
Doesn't seem to be done yet, I'd think?

**Comment by madhawav** [comment]
+1 for release. When will be able to see a new release?

**Comment by tito** [comment]
Done!

**Comment by tito** [comment]
Sorry for the delay, github notifications are so messy that important stuff are lost. Big kuddos for the team that got this message!

**Comment by madhawav** [comment]
@tito In the standard installation through PIP, where does the pyjnius.jar file  is created? Is their a mechanism to dynamically link it with Java program?

**Comment by tito** [comment]
Hi, the pyjnius.jar is only necessary for internal tests, and no, it's not included in the pip package. Never tought about it.
