### ISSUE TITLE
unexpeted output cjtp:r

### ISSUE THREAD

**Issue by nilday** [kivy/pyjnius#190]
I installed jnius on Centos .
when i running some programs ,there is some unexpeted output start with 'cjtp:r'.When i try to check the reason and run the example code.I find that happend even on example code.
Here is what it look like.
```
Python 2.7.3 (default, Oct 22 2014, 19:51:45) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jnius
>>> from jnius import autoclass
>>> autoclass('java.lang.System').out.println('Hello world')
Hello world
>>> Stack = autoclass('java.util.Stack')
>>> stack = Stack()
>>> stack.push('hello')
cjtp:r java/lang/String definition java/lang/String
'hello'
>>> stack.push('world')
cjtp:r java/lang/String definition java/lang/String
'world'
>>> print stack.pop()
cjtp:r java/lang/String definition java/lang/String
world
>>> print stack.pop()
cjtp:r java/lang/String definition java/lang/String
hello
```
this does not happened on my Mac.
Does anybody knows why?and how to fix it?

**Comment by nilday** [comment]
ok,I find out why by myself.
in file jnius_conversion.pxi line 128 :print('cjtp:r {0} definition {1}'.format(r, definition))

you must add this line between the time I install pyjnius on my mac and the server.

May be the line is added for debug,but it's the time to remove it.

**Comment by inclement** [comment]
@nilday Are you able to submit a PR to fix this? If not, one of us will do it.
