### ISSUE TITLE
__javaclass__ definition missing 

### ISSUE THREAD

**Issue by NetBUG** [kivy/pyjnius#193]
Hello!
I've build pyjnius from sources on Ubuntu 14.04 and get the following error after installation:
`root@staging:/tmp/pyjnius# make tests
(cd tests; env CLASSPATH=../build/test-classes:../build/classes PYTHONPATH=..: nosetests -v)
Failure: JavaException (__javaclass__ definition missing) ... ERROR
Failure: JavaException (__javaclass__ definition missing) ... ERROR`
...and all 16 tests fail.

I did to to have jnius_config module that is missing in pip package.

Detailed error:
`======================================================================
ERROR: Failure: JavaException (__javaclass__ definition missing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/pyjnius/tests/test_bad_declaration.py", line 5, in <module>
    from jnius import JavaException, JavaClass
  File "build/bdist.linux-x86_64/egg/jnius/__init__.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/jnius/reflect.py", line 14, in <module>
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__ (jnius/jnius.c:17159)
    meta.resolve_class(classDict)
  File "jnius/jnius_export_class.pxi", line 56, in jnius.MetaJavaClass.resolve_class (jnius/jnius.c:17474)
    raise JavaException('__javaclass__ definition missing')
JavaException: __javaclass__ definition missing`

**Comment by allen-ng** [comment]
Got the same error on Ubuntu 14.04

Here is my simple python code
```python
from jnius import autoclass
import jnius_config

jnius_config.set_classpath('.', '/usr/local/fem/plugins/*')
import jnius

Test = autoclass('Test.Test')
Test.hello()
```

and got this error:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from jnius import autoclass
  File "/usr/local/lib/python2.7/dist-packages/jnius-1.1_dev-py2.7-linux-x86_64.egg/jnius/__init__.py", line 13, in <module>
    from .reflect import *
  File "/usr/local/lib/python2.7/dist-packages/jnius-1.1_dev-py2.7-linux-x86_64.egg/jnius/reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__ (jnius/jnius.c:17159)
  File "jnius/jnius_export_class.pxi", line 56, in jnius.MetaJavaClass.resolve_class (jnius/jnius.c:17474)
jnius.JavaException: __javaclass__ definition missing

```

**Comment by xyzrico** [comment]
Hello Guys. I'm in the same situation with Lubuntu in virtual box from kivy installation.
Is there any solution to resolve this?

**Comment by pdelboca** [comment]
Which version of six.py are you using? Mine is working fine with six.py=1.10.0.

I know it's not a professional solution but for me worked upgrading the package in the virtual env with the following command:
`pip install --upgrade git+git://github.com/kivy/pyjnius.git`
My solution was working just fine but after trying to install another packages in the virtual env it started throwing this error. I think the problem was in the version of the `six.py` my venv was using because it was updated to 1.10 when upgrading jnius and it started working again.

**Comment by xyzrico** [comment]
I've tried 
`pip install --upgrade git+git://github.com/kivy/pyjnius.git`
But it's still not working. __javaclass__ definition missing

**Comment by kived** [comment]
Please upgrade the `six` package to at least version 1.7.0.

**Comment by xyzrico** [comment]
My version of six is already up to date. Now I've done

> pip install six=1.7.0

But got the same mistake.
If you want to see the [output...](https://drive.google.com/file/d/0ByqoS8VepSXFUVg2R1p2M3lzNEk/view?usp=sharing)

**Comment by kived** [comment]
The source shown in your traceback is from a pre-1.7.0 version.

[This is the code from 1.7.0](https://bitbucket.org/gutworth/six/src/35f6d89f826f63486214e4746af028ccaa088901/six.py?at=1.7.0&fileviewer=file-view-default#six.py-699):
````python
def with_metaclass(meta, *bases):
    """Create a base class with a metaclass."""
    # This requires a bit of explanation: the basic idea is to make a
    # dummy metaclass for one level of class instantiation that replaces
    # itself with the actual metaclass.  Because of internal type checks
    # we also need to make sure that we downgrade the custom metaclass
    # for one level to something closer to type (that's why __call__ and
    # __init__ comes back from type etc.).
    class metaclass(meta):
        __call__ = type.__call__
        __init__ = type.__init__
        def __new__(cls, name, this_bases, d):
            if this_bases is None:
                return type.__new__(cls, name, (), d)
            return meta(name, bases, d)
    return metaclass('temporary_class', None, {})
````

I confirmed that everything worked in 1.7.0 and later versions, and didn't work in pre-1.7.0 versions.

Your issue is most likely that you have two different versions of six installed. The one from Lubuntu (package `python-six`) is installed to `/usr/lib/python2.7/dist-packages`, which is what is listed in your traceback, and is not where pip installs. You should try removing the pip installed version and updating the system package via apt (don't uninstall `python-six` and keep the pip version, this package is necessary for many other system packages).

**Comment by xyzrico** [comment]
If I get you right, I should try

> pip uninstall six
 Or please can you juste paste me the commands I should type ?
The package python-six is installed. and my version of six got by pip is 1.7.0

**Comment by danielepantaleone** [comment]
Use `pip install six -U`. Also you can check what version of six you have currently installed by typing `pip freeze`.

**Comment by xyzrico** [comment]
My current installation of six is 1.10.0.

**Comment by xyzrico** [comment]
so... what should I do next ?

**Comment by kived** [comment]
Well if you still have this issue then you are still using a version of six < 1.7.0. Make sure you aren't using a virtualenv including an old version, or that you have something in your PYTHONPATH pointing to another location.

**Comment by xyzrico** [comment]
I'm not using virtualenv at all. But I found in my sys.path
a path to folder containing an old version of six (1.5.2). So I removed it.
Now when I type

> from jnius import autoclass, cast

I get an KeyError: 'JAVA_HOME'

**Comment by danielepantaleone** [comment]
Make sure to set your `JAVA_HOME` environment variable to the correct path of your java home. If you are on Windows you need also to add the path to the `jvm.dll` to system `Path`.
