### ISSUE TITLE
Import error on a clean install 

### ISSUE THREAD

**Issue by jsbruneau** [kivy/pyjnius#197]
The current state of the tree is broken on windows 10

Last commit a00ce3d3908082f828663bf2b029b50320221a10

`Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import jnius
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "jnius__init__.py", line 12, in <module>
> > >     from .jnius import *
> > > ImportError: No module named jnius`
##

**Comment by jk1ng** [comment]
Hi jsbruneau, you might want to ensure that your PATH and JAVA_HOME environment variables are configured correctly.

For windows, JAVA_HOME should point to your JDK root; and PATH should include a path that goes to your jvm.dll file -- which should be in your JAVA_HOME subdirectory of /jre/bin/server

Hope that helps.

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/pyjnius/issues/199#issuecomment-443013378.
