### ISSUE TITLE
Not able to install pyjnius on windows 7 and python 3.4. Error: jnius.obj lnk 2019

### ISSUE THREAD

**Issue by blue-o** [kivy/pyjnius#206]
I am installing pyjnius using pip install. I am getting the following error. 

jnius.obj : error LNK2019 : unresolved external symbol _JNI_CreateJavaVM@12...

How can I sort this out? Thanks.

**Comment by bevanj** [comment]
I am having the same issue, @blue-o how did you address this please?

**Comment by blue-o** [comment]
I couldn't solve it so I used a jar on the command line. And working from
there.
