### ISSUE TITLE
failed to import Cython error on windows 7, python 3.4

### ISSUE THREAD

**Issue by blue-o** [kivy/pyjnius#208]
I am trying to install pyjnius on windows 7, Python 3.4 but I am getting the following error. 

"failed to import Cython: module use of python34.dll conflicts with this version of python"

The cython version is 0.23.4. How can I fix it? 
##

**Comment by kived** [comment]
It looks like you have a conflict in Python versions. Did you do something like install Python 3.5 and copy the site-packages folder from 3.4?

**Comment by blue-o** [comment]
Thanks, Ryan.

I installed cython using pip and checked it installed in env but when I try
to install pyjnius using pip again, it couldn't recognize the installed
cython  so I cloned pyjnius and copied the cython module inside the
pyjnius.

Is it the problem? I only have python 2.7, 3.4 versions and I use 3.4 in
the virtual env.

Allison

**Comment by kived** [comment]
Well, I believe that error message means that you aren't running 3.4. Maybe something is messed up and you're actually running 2.7?

**Comment by blue-o** [comment]
I will sort it out. Thanks.
