### ISSUE TITLE
Getting JAVA_HOME KeyError while importing autoclass

### ISSUE THREAD

**Issue by parthibbiswas** [kivy/pyjnius#209]
Before formatting my computer, jnius used to work perfectly. But after formatting and reinstalling again, **from jnius import autoclass** doesn't seem to work anymore. Whenever I type that in Python shell, I get this error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *
  File "/usr/local/lib/python2.7/dist-packages/jnius/reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__ (jnius/jnius.c:17159)
  File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class (jnius/jnius.c:17555)
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv (jnius/jnius.c:3320)
  File "jnius/jnius_jvm_dlopen.pxi", line 89, in jnius.get_platform_jnienv (jnius/jnius.c:3248)
  File "jnius/jnius_jvm_dlopen.pxi", line 48, in jnius.create_jnienv (jnius/jnius.c:2647)
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'JAVA_HOME'

```

My JAVA_HOME is set to /usr/lib/jvm/java-7-openjdk-amd64

Do I need to add something else to PATH? Do I need to set path for Python?

**Comment by parthibbiswas** [comment]
Ah, nevermind. I had to modify .bashrc file to make PATHs permanent.

**Comment by darleison** [comment]
please can you post the line of your .bashrc file?

**Comment by brandomr** [comment]
likewise, @parthibbiswas it would be helpful to see how you resolved this as I am facing the same error.

**Comment by jmstfv** [comment]
@darleison @brandomr I don't know whether you managed to find a solution, but that worked for me:

- Open ~/.bashrc file

- copy this line` export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 export PATH=$JAVA_HOME/bin:$PATH` **(path / or java version may differ, make sure to check it before copying)**
- save the file and log out
Hope that helps:)

**Comment by ngengesenior** [comment]
It worked for me...

**Comment by v6** [comment]
// , This worked for me, too. I ran into this while attempting GreenAddress's recovery instructions with Electron Cash.

**Comment by JuggernautPanda** [comment]
I have the issue even though I have set JAVA_HOME.

Ubuntu 16.04
Python 3.5

**Comment by Petar-Luketina** [comment]
@JuggernautPanda have you found a way around the problem? I'm getting the same error after the suggestions above.

```
pl@Petar:~$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
```
Above code suggests the move was successful but didn't change the error.

**Comment by JuggernautPanda** [comment]
> @JuggernautPanda have you found a way around the problem? I'm getting the same error after the suggestions above.
> 
> ```
> pl@Petar:~$ echo $JAVA_HOME
> /usr/lib/jvm/java-8-openjdk-amd64
> ```
> Above code suggests the move was successful but didn't change the error.

Hello Petar.

Yes. I did manage to solve it but with a twist -

I did this and it worked.

import os
try:
	from jnius import autoclass

except KeyError:
	os.environ['JDK_HOME'] = "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
	os.environ['JAVA_HOME'] = "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
	from jnius import autoclass

**Comment by sagarhm** [comment]
![image](https://user-images.githubusercontent.com/55372566/120210023-f34aca00-c24c-11eb-8bca-8c9c3eb946f6.png)
