### ISSUE TITLE
How to compile a distribution with -m "pyjnius kivy"?

### ISSUE THREAD

**Issue by parthibbiswas** [kivy/pyjnius#211]
How do I do this when .distribute.sh don't work anymore? Shouldn't the docs be updated for this since .distribute.sh is obsolete now? Or am I missing something here? O.o
##

**Comment by inclement** [comment]
Yes, the docs need updating for compatibility with python-for-android master. If you use the old python-for-android toolchain, the instructions still apply.

It should be easy to translate the instructions to the new toolchain, though; now it's just `pyjnius,kivy` in the requirements line.

**Comment by tito** [comment]
If kivy is included, pyjnius will be automatically, as kivy require pyjnius. So there is no need to add it into the requirements
