### ISSUE TITLE
jnius\jnius.c(4205) : error C2065: 'const_char' : undeclared identifier ,install on windows

### ISSUE THREAD

**Issue by apologit** [kivy/pyjnius#214]
Hi! My python version is  2.7 (WIN32),Cython's is 0.24.A error occoured when installing pyjnius.I don't know the right way to install pyjnius successfully.Please help me.Thx

WIN7 X64
D:\software\python\pyjnius-master>python setup.py install
use cython
WARNING: Not able to assign machine() = AMD64 to a cpu value!
         Using cpu = 'i386' instead!
C:\Program Files\Java\jdk1.8.0_20\include\win32
running install
running bdist_egg
running egg_info
writing requirements to jnius.egg-info\requires.txt
writing jnius.egg-info\PKG-INFO
writing top-level names to jnius.egg-info\top_level.txt
writing dependency_links to jnius.egg-info\dependency_links.txt
reading manifest file 'jnius.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*COPYING'
writing manifest file 'jnius.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
cythoning jnius\jnius.pyx to jnius\jnius.c
warning: jnius\jnius.pyx:2:0: __getslice__, __setslice__, and __delslice__ are
ot supported by Python 3, use __getitem__, __setitem__, and __delitem__ instea
building 'jnius' extension
C:\Users\WANGHONGXIA651\AppData\Local\Programs\Common\Microsoft\Visual C++ for
ython\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Fil
\Java\jdk1.8.0_20\include" "-IC:\Program Files\Java\jdk1.8.0_20\include\win32"
IC:\Python27\include -IC:\Python27\PC /Tcjnius\jnius.c /Fobuild\temp.win32-2.7
elease\jnius\jnius.obj
jnius.c
jnius\jnius.c(3225) : warning C4047: 'function' : 'void **' differs in levels
 indirection from 'JNIEnv **'
jnius\jnius.c(3225) : warning C4022: 'function through pointer' : pointer mism
ch for actual parameter 2
jnius\jnius.c(4205) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(4205) : error C2059: syntax error : ')'
jnius\jnius.c(4214) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(4214) : error C2059: syntax error : ')'
jnius\jnius.c(4223) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(4223) : error C2059: syntax error : ')'
jnius\jnius.c(4232) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(4232) : error C2059: syntax error : ')'
jnius\jnius.c(5508) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(5508) : error C2059: syntax error : ')'
jnius\jnius.c(7713) : warning C4244: '=' : conversion from 'long' to 'jchar',
ssible loss of data
jnius\jnius.c(9157) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(9157) : error C2059: syntax error : ')'
jnius\jnius.c(9309) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(9309) : error C2059: syntax error : ')'
jnius\jnius.c(9360) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(9360) : error C2059: syntax error : ')'
jnius\jnius.c(9411) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(9411) : error C2059: syntax error : ')'
jnius\jnius.c(11992) : error C2059: syntax error : ')'
jnius\jnius.c(12043) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(12043) : error C2059: syntax error : ')'
jnius\jnius.c(12091) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(12091) : error C2059: syntax error : ')'
jnius\jnius.c(12139) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(12139) : error C2059: syntax error : ')'
jnius\jnius.c(12187) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(12187) : error C2059: syntax error : ')'
jnius\jnius.c(12197) : warning C4244: '=' : conversion from 'long' to 'jchar',
ossible loss of data
jnius\jnius.c(12235) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(12235) : error C2059: syntax error : ')'
jnius\jnius.c(12356) : error C2061: syntax error : identifier '__pyx_f_5jnius_c
nvert_pyarray_to_java'
jnius\jnius.c(12356) : error C2059: syntax error : ';'
jnius\jnius.c(12356) : error C2059: syntax error : 'type'
jnius\jnius.c(17440) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(17440) : error C2059: syntax error : ')'
jnius\jnius.c(17449) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(17449) : error C2059: syntax error : ')'
jnius\jnius.c(17490) : warning C4047: '=' : 'jobject' differs in levels of indi
ection from 'jobject *'
jnius\jnius.c(17499) : warning C4047: '=' : 'jobject' differs in levels of indi
ection from 'jclass *'
jnius\jnius.c(19626) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(19626) : error C2059: syntax error : ')'
jnius\jnius.c(30466) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(30466) : error C2059: syntax error : ')'
jnius\jnius.c(31239) : error C2061: syntax error : identifier '__pyx_f_5jnius_i
voke0'
jnius\jnius.c(31239) : error C2059: syntax error : ';'
jnius\jnius.c(31239) : error C2059: syntax error : 'type'
jnius\jnius.c(31637) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(31637) : error C2059: syntax error : ')'
jnius\jnius.c(31646) : error C2065: 'const_char' : undeclared identifier
jnius\jnius.c(31646) : error C2059: syntax error : ')'
error: command 'C:\\Users\\WANGHONGXIA651\\AppData\\Local\\Programs\\Common\\Mi
rosoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by apologit** [comment]
I have solved it.I install cython with pip.Then the problem had been solved.

**Comment by vslotman** [comment]
I've got the same issue on Linux, although re-installing Cython doesn't help here. 

I tried to install pyjnius on a clean install of Ubuntu 14.04 LTS and I keep getting the **'const_char' : undeclared identifier error.**

Reinstall of Cython through pip (version 0.23.4) or apt (version 0.24)  does not help. Also pyjnius from pip and github/master have the same issue.

uname -a: Linux tester 3.16.0-67-generic #87~14.04.1-Ubuntu SMP Fri Mar 11 00:26:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)


I installed pyjnius on another machine some weeks ago without problems. On this machine I can build the pip and github/master-version of pyjnius without errors.

uname -a: Linux aln-lx911653 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
Cython version: 0.23.4

**Comment by jmuhlich** [comment]
I am seeing the same error message. It seems to have started with cython 0.24. With cython 0.23.5 I do not get this error. I think apologit's switch to pip "fixed" the problem because cython 0.24 hadn't yet been uploaded to pypi so he ended up using 0.23 which seems not to cause this problem.

**Comment by jmuhlich** [comment]
Oops, didn't see this issue had been closed. Shall I open a new issue @tito ?

**Comment by inclement** [comment]
I've opened a specific issue for the problem at https://github.com/kivy/pyjnius/issues/219
