### ISSUE TITLE
can't import jnius : The specified module could not be found

### ISSUE THREAD

**Issue by apologit** [kivy/pyjnius#216]
I tried to test import jnius when get  it installed.But I met the problem below.Please help me.

PYTHON: 2.7.11  64bit 
JDK:jdk1.8.0_20  64bit

C:\Python27\python.exe D:/svn/testdev/testyyy/test_java.py
Traceback (most recent call last):
  File "D:/svn/testdev/testyyy/test_java.py", line 2, in <module>
    from jnius import autoclass
  File "build\bdist.win-amd64\egg\jnius__init__.py", line 12, in <module>
  File "build\bdist.win-amd64\egg\jnius\jnius.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\jnius\jnius.py", line 6, in **bootstrap**
**ImportError: DLL load failed:The specified module could not be found**
##

**Comment by chiangliam** [comment]
add "C:\Program Files\Java\jdk1.XXXX\jre\bin\client"  
or "C:\Program Files\Java\jdk1.XXXX\jre\bin\server" to your Path of Windows environment

**Comment by lovebair2022** [comment]
Have you solve it?I am facing a same problem.

**Comment by mostafa** [comment]
Didn't work for me either!

**Comment by zlulan** [comment]
add "C:\Program Files\Java\jdk1.XXXX\jre\bin\client"
or "C:\Program Files\Java\jdk1.XXXX\jre\bin\server" to your Path of Windows environment

**Comment by Csega** [comment]
Actually, there is a different way if you don't want to set the environment variables or you don't have administrator access to the machine you are working on. Put this at the beginning of your Python script:

```Python
import os
 
os.environ['JDK_HOME'] = "C:\Program Files\Java\jdk1.XXX"
os.environ['JAVA_HOME'] = "C:\Program Files\Java\jdk1.XXX"

os.environ['PATH'] += ';C:\\Program Files\\Java\\jdk1.XXX\\jre\\bin\\server\\;C:\\Program Files\\Java\\jdk1.XXX\\bin\\;path\to\your.jar'
```

Cheers!

**Comment by antonyjosepha** [comment]
Install Microsoft Visual C++ 2010 Redistributable Package may be this will work.

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/pyjnius/issues/199#issuecomment-443013378.

**Comment by RameshwarGupta97** [comment]
> Actually, there is a different way if you don't want to set the environment variables or you don't have administrator access to the machine you are working on. Put this at the beginning of your Python script:
> 
> ```python
> import os
>  
> os.environ['JDK_HOME'] = "C:\Program Files\Java\jdk1.XXX"
> os.environ['JAVA_HOME'] = "C:\Program Files\Java\jdk1.XXX"
> 
> os.environ['PATH'] += ';C:\\Program Files\\Java\\jdk1.XXX\\jre\\bin\\server\\;C:\\Program Files\\Java\\jdk1.XXX\\bin\\;path\to\your.jar'
> ```
> 
> Cheers!

That worked smoothly for me. I had to remove jar path reference from there as wasn't sure which jar path it is expecting.
