### ISSUE TITLE
pyjinius and NFC

### ISSUE THREAD

**Issue by pedefe** [kivy/pyjnius#222]
Hello,

Do you have an example for NFC interface ?
I see that some code like following can be used:

```
PythonActivity = autoclass('org.renpy.android.PythonActivity')
Intent = autoclass('android.content.Intent')
```

But after ... how to enable stream (or tag) detection and get the data ?
Best regards
##

**Comment by tito** [comment]
Hi, use the mailing list for question like that. It has nothing to do with pyjnius itself / issues :)
