### ISSUE TITLE
Pyjnius installation error for Python 3 or 3.5 on lubuntu

### ISSUE THREAD

**Issue by woth2k3** [kivy/pyjnius#232]
I've got the following error during the installation for Python 3 or 3.5 on lubuntu
(I also discussed on the kivy irc channel and another user has the same error, so I'm not sure if it's my error or something else):

jnius/jnius.c: At top level:
jnius/jnius.c:41230:2: error: #error **getslice**, **setslice**, and **delslice** not supported in Python 3.
 #error **getslice**, **setslice**, and **delslice** not supported in Python 3.

The whole installation log:

:~/Desktop/pyjnius-master$ sudo python3 setup.py install
[sudo] password for: 
/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/setuptools/dist.py:285: UserWarning: Normalizing '1.1-dev' to '1.1.dev0'
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing dependency_links to jnius.egg-info/dependency_links.txt
writing requirements to jnius.egg-info/requires.txt
writing top-level names to jnius.egg-info/top_level.txt
writing jnius.egg-info/PKG-INFO
reading manifest file 'jnius.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '_COPYING'
writing manifest file 'jnius.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'jnius/jnius.c' Cython extension (up-to-date)
building 'jnius' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/jvm/java-8-openjdk-amd64/include -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux -I/usr/include/python3.5m -c jnius/jnius.c -o build/temp.linux-x86_64-3.5/jnius/jnius.o
jnius/jnius.c: In function ‘__pyx_f_5jnius_get_jnienv’:
jnius/jnius.c:3271:68: warning: passing argument 2 of ‘(_**pyx_v_5jnius_jvm)->AttachCurrentThread’ from incompatible pointer type [-Wincompatible-pointer-types](__pyx_v_5jnius_jvm[0])->AttachCurrentThread(__pyx_v_5jnius_jvm, (&__pyx_v_en
                                                                    ^
jnius/jnius.c:3271:68: note: expected ‘void *_’ but argument is of type ‘const struct JNINativeInterface_ *_*’
jnius/jnius.c: In function ‘__pyx_pf_5jnius_13MetaJavaClass_4resolve_class’:
jnius/jnius.c:16394:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types](__pyx_v_jargs[0]) = ((jobject *)__pyx_v_classLoader);
                              ^
jnius/jnius.c:16403:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types](__pyx_v_jargs[1]) = __pyx_v_interfaces;
                              ^
jnius/jnius.c: At top level:
jnius/jnius.c:41230:2: error: #error __getslice**, **setslice**, and **delslice** not supported in Python 3.
 #error **getslice**, **setslice**, and **delslice** not supported in Python 3.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
##

**Comment by amigo00678** [comment]
Hey! Have a look at this [PR](https://github.com/kivy/pyjnius/pull/239). Quick fix, works only for python 3.5 (not 2.7).

**Comment by madhawav** [comment]
I have got a similar error when I tried to install to both Python 2.7 and Python 3.x using _same local copy_ of code. 

Solution:
--
Before an installation, check whether the following file exists and if so, delete it.
> pyjnius/jnius/jnius.c

The above file is an auto-generated temporary file which should be deleted before making an installation for a different version of Python.

**Comment by misl6** [comment]
Closing as the issue refers on a old version of `pyjnius`, and we do not support Python **3.5** anymore.
Feel free to re-open the issue if it persists on a recent `pyjnius` version (on a supported Python 3 version)
