### ISSUE TITLE
jnius can't open image file that was included in buildozer.spec

### ISSUE THREAD

**Issue by nmz787** [kivy/pyjnius#236]
I have an image, a .Java file that calls class methods found in a .so file... I managed to get `autoclass` to find my .Java file class, which calls the .so file methods. When the .Java file tries to open the JPG image which I included in the buildozer.spec, the file cannot be found. Even using Java-based directory listing, I cannot see the JPG (which Python OS module reports as present).

Here is where I was previously listing the dir in Python:
https://gist.github.com/nmz787/d0e71593240df63436d15037aff46c3e#file-main-py-L91

Here is where I was calling Java to list some dirs:
https://gist.github.com/nmz787/d0e71593240df63436d15037aff46c3e#file-main-py-L122

and another try at listing some dirs:
https://gist.github.com/nmz787/d0e71593240df63436d15037aff46c3e#file-doit-java-L93

and here's the logcat with the FileNotFoundException at the end (also shows the buildozer output at the beginning, and a background service for DualLens which isn't related but shows that the interesting-to-me .SO calls should be found once I get past this file issue):
https://paste.pound-python.org/show/EsQKwK6nfRUD26YSLPtM/
##

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/plyer/pull/491, Python handles the file paths as it's handled on Unix-like OS, however Android has a separate thing for that. Try to look at the related PR. Anyway, it's not a PyJNIus issue, but an Android "issue" because they do stuff differently.
