### ISSUE TITLE
'ant' Command not found when running 'make'

### ISSUE THREAD

**Issue by cuongtv89ks** [kivy/pyjnius#237]
I'm trying to install pyjnius. 
Before intalling, my JAVA_HOME is set:
`export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH`

then when I run 'make', got error:

> ant all
> make: ant: Command not found
> Makefile:19: recipe for target 'build_ext' failed
> make: **\* [build_ext] Error 127

I dont know how to fix it?
##

**Comment by danielepantaleone** [comment]
Looks like you don't have [ant](http://ant.apache.org) installed on your system: `make: ant: Command not found`

**Comment by cuongtv89ks** [comment]
after installing ant, then I got this error: 

> ant all
> Buildfile: /home/cuongtv89/pyjnius/build.xml
> 
> compile:
> 
> BUILD FAILED
> /home/cuongtv89/pyjnius/build.xml:8: Directory /home/cuongtv89/pyjnius/build/classes creation was not successful for an unknown reason
> 
> Total time: 0 seconds
> Makefile:19: recipe for target 'build_ext' failed
> make: *** [build_ext] Error 1
> 

this one already had issue on pyjnus but I still dont know how to fix this bug

**Comment by deepzf** [comment]
you have no rights to creation directory,use sudo or chmod the rights to fix it

**Comment by kakkarotssj** [comment]
Try steps , on above referenced issue

**Comment by KeyWeeUsr** [comment]
About the `127` error code: https://stackoverflow.com/a/1763178/5994041, which is a missing binary on your system as said above. The rest is (as @deepzf said) most likely a permission issue. Either use `chmod` to own the directory you are trying to create such folder into or use `sudo` to "hide" the issue. (The permissions will still cause issues later).
