### ISSUE TITLE
JAVA interface class implementation issue

### ISSUE THREAD

**Issue by shashankkhare** [kivy/pyjnius#243]
Using python2.7 and pyjnius to develop an Android App. I am implementing a JAVA interface class android.bluetooth.le.ScanCallback for BLE support. Whenever I try to instantiate the python class it gives an error "JVM error: android.bluetooth.le.ScanCallback is not an abstract class". I have checked the documentation and android.bluetooth.le.ScanCallback is an abstract class.  
Here is my code which implements the abstract Java class. 

```
class ScanCallback(PythonJavaClass):
    **javainterfaces** = ['android/bluetooth/le/ScanCallback'] 
    def **init**(self, scanCallback, batchCallback=None, errorCallback=None):
        super(ScanCallback, self).**init**()
        self.batchCallbk = batchCallback
        self.scanCallbk = scanCallback
        self.errorCallbk = errorCallback
        pass
    @java_method ('(L/java/utils/List<ScanResult>/)V')
    def onBatchScanResults(self,results): 
        print dir(results)
    @java_method ('(I)V')  
    def onScanFailed(self, errorCode):
        print "failed to scan" + str(errorCode)
        raise ValueError(str(errorCode))
```
```
@java_method ('(IL/android/bluetooth/le/ScanResult)V')
def onScanResult(self, callbackType, result):
    print dir(result)
```
##

**Comment by tito** [comment]
Pyjnius support implementation of Java interfaces, NOT abstract classes.

**Comment by kamathln** [comment]
is abstract class implementation support planned?

**Comment by tkeske** [comment]
Same question.

Is it even technically possible to have support for implementation of Java abstract classes with pyjnius? 

Or it is better solution to implement this type of android callbacks in pure Java, and then expose the results of callback via public getter methods to pyjnius?
