### ISSUE TITLE
setup fails: unknown file type '.pxi' (from 'jnius/jni.pxi')

### ISSUE THREAD

**Issue by rhoerbe** [kivy/pyjnius#244]
This happens with in building 'jnius' extension error.
Tested with centos7 + py27, py34, py35.

I published a repo to reproduce the issue: https://github.com/rhoerbe/pyjnius-deploytest.git

The log can be viewed here:
https://travis-ci.org/rhoerbe/pyjnius-deploytest  (e.g. line 1496)
##

**Comment by rhoerbe** [comment]
Workaround: install Cython==0.24

**Comment by tito** [comment]
Pyjnius require Cython :)

**Comment by mixmastamyk** [comment]
Please reopen this, just had the same problem.

The site recommends Cython .25 for Kivy 1.10.  

I had to go back to .24 to get things to build again after wasting a week on it.

**Comment by KeyWeeUsr** [comment]
@mixmastamyk [where?](http://pyjnius.readthedocs.io/en/latest/installation.html?highlight=cython) I know about [`1.10.1`](https://kivy.org/docs/installation/installation-linux.html#common-dependencies).

**Comment by mixmastamyk** [comment]
That's the one I'm familiar with, yes.

**Comment by mixmastamyk** [comment]
Went to .24.1 actually and it is working again.

**Comment by KeyWeeUsr** [comment]
There's no mention about `1.10` and Cython `0.25` at the same place. There was [a change](https://github.com/kivy/kivy/commit/ced5e6a7a6474b72722cef4e3470ed6bc58d1793) in Kivy that requires a newer version of Cython (`0.25.2+`), however it's only in the master branch (`1.10.1`) and the stable (`1.10.0`) works fine even with older versions.

I know about no other changes that would prevent compiling by default.

**Comment by mixmastamyk** [comment]
Just checked, I have 1.10.0.

Did the pyjnius build get fixed in/by 1.10.1?  If not the problem persists.
