### ISSUE TITLE
missing import os in jnius/__init__.py - there should be a CI workflow for pyjnius

### ISSUE THREAD

**Issue by rhoerbe** [kivy/pyjnius#245]
File "/usr/lib64/python3.4/site-packages/jnius-1.1.dev0-py3.4-linux-x86_64.egg/jnius/__init__.py", line 42, in <module>
    if "ANDROID_ARGUMENT" in os.environ:
NameError: name 'os' is not defined

May I suggest to activate a CI work flow to verify properties of commits and pull requests int he master branch? I have published a basic Travis-CI setup for py 2.7/3.4/3.5 with centos7 in this project:
https://github.com/rhoerbe/pyjnius-deploytest.git
AFAIK Travis can also be used to test android and OSX.

**Comment by rhoerbe** [comment]
And could be configured to publish a new version on PyPi once tests are successful.

**Comment by akshayaurora** [comment]
@rhoerbe the issue is fixed in master.
