### ISSUE TITLE
Usage on termux 

### ISSUE THREAD

**Issue by kamathln** [kivy/pyjnius#247]
Please document how to use pyjnius on [Termux](https://github.com/termux/termux-app)

**Comment by romaia** [comment]
Is it even possible to use pjnius from within a termux environment?

**Comment by KeyWeeUsr** [comment]
Pyjnius depends on Python shared object(s) being available on the system *and* java shared objects being available too. For Android we use cross-compiled CPython with `libpython.<versions>.so` and Java Native Interface provided by P4A and/or SDL2. P4A runs the python code by calling C API of CPython library and not via `python something.py`.

If you have `python` binary working and accessible, you'll be able to run it as if on desktop. If not, then only by some other program interfacing with the `libpython` and calling the particular C API so start a Python program.

PyJNIus is not a standalone library, but a library dynamically linked against CPython and JNI.

**Comment by traverseda** [comment]
Right, so this here is the python package that would need to be patched? Any guidance on that?

https://github.com/termux/termux-packages/tree/master/packages/python

**Comment by traverseda** [comment]
And presumably we'd need to hook into https://github.com/termux/termux-api in order to make java shared objects work. That's a lot thornier of an issue, but if this is something pyjnius is interested in, we may be able to get help from the other side as well.
