### ISSUE TITLE
Error with pyjnius installing : error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by xyzrico** [kivy/pyjnius#248]
Hello. I hope you are okay.
I'm trying to install pyjnius on my computer. I am under Kali linux.
When I try the command 

> python setup.py build

I get the error
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
I get the same error with

> sudo pip install pyjnius

Please can someone help me ?
Here is the full screen

`/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.1-dev' to '1.1.dev0'
  normalized_version,
running build
running build_py
running build_ext
cythoning jnius/jnius.pyx to jnius/jnius.c
/usr/lib/python2.7/genericpath.py:79: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  s1 = min(m)

Error compiling Cython file:
------------------------------------------------------------
...
# 7.20 General utilities <stdlib.h>

# deprecated cimports for backwards compatibility:
from libc.string cimport const_char, const_void
^
------------------------------------------------------------

/usr/local/lib/python2.7/dist-packages/Cython/Includes/libc/stdlib.pxd:4:0: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 118, in analyse_declarations: ModuleNode(stdlib.pxd:1:0,
    full_module_name = u'libc.stdlib',
    is_pxd = True)
File 'Nodes.py', line 425, in analyse_declarations: StatListNode(stdlib.pxd:4:0)
File 'Nodes.py', line 7403, in analyse_declarations: FromCImportStatNode(stdlib.pxd:4:0,
    imported_names = [...]/2,
    module_name = u'libc.string')

Compiler crash traceback from this point on:
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py", line 7403, in analyse_declarations
    module_scope = env.find_module(self.module_name, self.pos, relative_level=self.relative_level)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Symtab.py", line 1188, in find_module
    module_name, relative_to=relative_to, pos=pos, absolute_fallback=absolute_fallback)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 178, in find_module
    pxd_pathname = self.find_pxd_file(qualified_name, pos)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 239, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 280, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 30, in wrapper
    res = cache[args] = f(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 148, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

Error compiling Cython file:
------------------------------------------------------------
...

__all__ = ('JavaObject', 'JavaClass', 'JavaMethod', 'JavaField',
           'MetaJavaClass', 'JavaException', 'cast', 'find_javaclass',
           'PythonJavaClass', 'java_method', 'detach')

from libc.stdlib cimport malloc, free
^
------------------------------------------------------------

jnius/jnius.pyx:92:0: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 118, in analyse_declarations: ModuleNode(jnius.pyx:2:0,
    doc = u'\nJava wrapper\n============\n\nWith this module, you can create Python class that reflects a Java class, and use\nit directly in Python.\n\nExample with static method\n--------------------------\n\nJava::\n\n    package org.test;\n    public class Hardware {\n        static int getDPI() {\n            return metrics.densityDpi;\n        }\n    }\n\nPython::\n\n    class Hardware(JavaClass):\n        __metaclass__ = MetaJavaClass\n        __javaclass__ = \'org/test/Hardware\'\n        getDPI = JavaStaticMethod(\'()I\')\n\n    Hardware.getDPI()\n\n\nExample with instance method\n----------------------------\n\nJava::\n\n    package org.test;\n    public class Action {\n        public String getName() {\n            return new String("Hello world")\n        }\n    }\n\nPython::\n\n    class Action(JavaClass):\n        __metaclass__ = MetaJavaClass\n        __javaclass__ = \'org/test/Action\'\n        getName = JavaMethod(\'()Ljava/lang/String;\')\n\n    action = Action()\n    print action.getName()\n    # will output Hello World\n\n\nExample with static/instance field\n----------------------------------\n\nJava::\n\n    package org.test;\n    public class Test {\n        public static String field1 = new String("hello");\n        public String field2;\n\n        public Test() {\n            this.field2 = new String("world");\n        }\n    }\n\nPython::\n\n    class Test(JavaClass):\n        __metaclass__ = MetaJavaClass\n        __javaclass__ = \'org/test/Test\'\n\n        field1 = JavaStaticField(\'Ljava/lang/String;\')\n        field2 = JavaField(\'Ljava/lang/String;\')\n\n    # access directly to the static field\n    print Test.field1\n\n    # create the instance, and access to the instance field\n    test = Test()\n    print test.field2\n\n',
    full_module_name = 'jnius')
File 'Nodes.py', line 425, in analyse_declarations: StatListNode(jnius.pyx:88:0)
File 'Nodes.py', line 7424, in analyse_declarations: FromCImportStatNode(jnius.pyx:92:0,
    imported_names = [...]/2,
    module_name = u'libc.stdlib')

Compiler crash traceback from this point on:
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Nodes.py", line 7424, in analyse_declarations
    name, relative_to=module_scope, pos=self.pos, absolute_fallback=False)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 178, in find_module
    pxd_pathname = self.find_pxd_file(qualified_name, pos)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 239, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Compiler/Main.py", line 280, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 30, in wrapper
    res = cache[args] = f(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Utils.py", line 148, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
building 'jnius' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-U_f_pV/python2.7-2.7.13~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/jvm/java-7-openjdk-amd64/include -I/usr/lib/jvm/java-7-openjdk-amd64/include/linux -I/usr/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
jnius/jnius.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by kakkarotssj** [comment]
#241 
Try on these steps

**Comment by xyzrico** [comment]
Oh. It worked !
Amazing. Thank you.
