### ISSUE TITLE
inherit a java class

### ISSUE THREAD

**Issue by razzbee** [kivy/pyjnius#251]
Hello , I need to override some java methods but the only way to go about it is to inherit that class , I have tried inheriting the java class from autoclass but seems not to work example:
```
WebViewClient = autoclass('android.webkit.WebViewClient') 

class myWebviewClient(WebViewClient):
    
     #Some Methods to Override 
```

This is the error I get 
12-21 01:47:28.921  9862  9893 I python  :      class myWebviewClient(WebViewClient):
12-21 01:47:28.921  9862  9893 I python  :    File "jnius/jnius_export_class.pxi", line 43, in jnius.jnius.MetaJavaClass.__new__ (jnius/jnius.c:17248)
12-21 01:47:28.922  9862  9893 I python  :    File "jnius/jnius_export_class.pxi", line 56, in jnius.jnius.MetaJavaClass.resolve_class (jnius/jnius.c:17575)
12-21 01:47:28.923  9862  9893 I python  :  jnius.jnius.JavaException: __javaclass__ definition missing
12-21 01:47:29.001  9862  9893 I python  : Python for android ended.

when I set the 
__javaclass__ = 'android/webkit/WebViewClient'
it still doesnt work , Please help me

**Comment by tito** [comment]
As per documentation, inheritance is not supported in Pyjnius. Only java interface can be implemented cause JNI allow it. JNI have nothing for declaring class and adding method onto it.
