### ISSUE TITLE
jnius.JavaException: Class not found 'android/util/DisplayMetrics'

### ISSUE THREAD

**Issue by kakkarotssj** [kivy/pyjnius#260]
When  I do    >>> Stack = autoclass('java.util.Stack') , it works fine. But when i use Android API's like
DisplayMetrics = autoclass('android.util.DisplayMetrics'), it gives an error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius/reflect.py", line 154, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass (jnius/jnius.c:16599)
    raise JavaException('Class not found {0!r}'.format(name))
jnius.JavaException: Class not found 'android/util/DisplayMetrics'

I have a guess, why is this happening , because when i do android.util.* , pyjnius looks for a .class but when i checked in my system after installing android, these all modules are .java.
Please help me find a solution.
Thanks

**Comment by tito** [comment]
You need an android device to be able to execute this code. You cannot import android class on your desktop :)
