### ISSUE TITLE
Bug in receiving asynchronous callbacks from Java Threads 

### ISSUE THREAD

**Issue by madhawav** [kivy/pyjnius#276]
Hi,

I am receiving the following error when I receive callback events from Background Java Threads (threads which I create manually in Java) to Python.
> take_gil: NULL tstate

This happens when I use Python 3.5 or 3.6 without debugger. When debugging is used, the error would not appear. Also, the code works fine with Python 3.3. 

I believe this error is due to the condition explained at below link, which seem to be a bug introduced in Python 3.4+.
https://bugs.python.org/issue20891

Has anyone figured-out a workaround for this issue? The workaround they suggest in above link is  to call PyEval_InitThreads() on non Python threads. How can we implement the above workaround with pyjnius?

**Comment by Julian-O** [comment]
Bug fixed in all Python version supported. Closing as stale.
