### ISSUE TITLE
Windows 10 Home 64bit: Tests as well as minimum example fail with fatal JRE error 

### ISSUE THREAD

**Issue by hanslovsky** [kivy/pyjnius#279]
I am not very familiar with windows but in order to distribute a python package that depends on PyJNIus on all major OSes (Windows, OSX, Linux) I tried to build PyJNIus on a Windows 10 Home Edition 64 bit machine.

I obtained python 3 through conda and followed (roughly) these steps:
```
 - Install conda
 - Install PyJNIus dependencies through conda and/or pip
 - Install OpenJDK `1.8.0_131`
 - install Apache ant
 - install visual cpp build tools
 - Instead of make run commands in Makefile by hand
   - `ant all`
   - `python setup.py build_ext --inplace -f`
   - for tests:
     - `cd tests`
     - `set CLASSPATH=..\build\test-classes;..\build\classes`
     - `set PYTHONPATH=..`
     - `nosetests -v > nosetests.log 2>&1` (compare nosetests.log in this gist)
```
The last command (nosetests) triggers this error message (I skipped the nosetests output but you can find that [here](https://gist.github.com/hanslovsky/69ab3d007c09749ce400b678829eea18#file-nosetests-log):
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff4facdff4, pid=13156, tid=0x0000000000002f84
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [jnius.cp36-win_amd64.pyd+0x1dff4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Zottel\Downloads\pyjnius-master\pyjnius-master\tests\hs_err_pid13156.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Similarly, when I try to implement a Java interface in Python and pass it to a Java method like this:
```python
# See fail.log for error message
import jnius_config
jnius_config.add_classpath(r'C:\Users\Zottel\git\pyjnius\build\pyjnius.jar')
from jnius import PythonJavaClass, java_method, autoclass
class AddOne( PythonJavaClass ):
    __javainterfaces__ = ['java/util/function/IntUnaryOperator']
    def __init__(self):
        super( AddOne, self ).__init__()
    @java_method('(I)I')
    def applyAsInt( self, operand ):
        return operand + 1
    
stream = autoclass('java.util.stream.IntStream').range( 0, 10 )
ao = AddOne()
stream.map( ao ).toArray()
```
I see this failure mode:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff4a2adff4, pid=10772, tid=0x0000000000000ff4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [jnius.cp36-win_amd64.pyd+0x1dff4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Zottel\hs_err_pid10772.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

I collected all of the above in a gist:
https://gist.github.com/hanslovsky/69ab3d007c09749ce400b678829eea18

**Comment by jpsacha** [comment]
+1

**Comment by hanslovsky** [comment]
One and a half weeks ago, @skalarproduktraum helped me debugging this issue a little more and we were able to narrow it down and I assume now that [these lines in `jnius/jnius_proxy.pxi`](https://github.com/kivy/pyjnius/blob/master/jnius/jnius_proxy.pxi#L76-L154) and [these lines in `jnius/jnius_conversion.pxi`](https://github.com/kivy/pyjnius/blob/master/jnius/jnius_conversion.pxi#L322-L447) cause the issue. Unfortunately, I do not have a windows machine, so I do not know when I will be able to follow up on this.

Could you comment on whether or not this is an issue that is relevant for the kivy core developers? If I am not mistaken, pyjnius was developed with Android/Unix in mind so Windows support might be limited.

**Comment by madhawav** [comment]
+1 
having the same issue on Windows 10 Pro 64 bit with Python 3.6 and JDK 8.

**Comment by madhawav** [comment]
I have made the PR #290 which should fix the discussed issue. Can someone kindly review it and merge?

**Comment by hanslovsky** [comment]
Great work @madhawav Thank you for taking your time and fixing it!

**Comment by hanslovsky** [comment]
I was able to test and confirm that the issue is now resolved. Thanks again for @madhawav for putting in the work to resolve this!

**Comment by madhawav** [comment]
@hanslovsky Your most welcome!
