### ISSUE TITLE
 Supplementary unicode characters are mangled or throw UnicodeDecodeError

### ISSUE THREAD

**Issue by brandonherzog** [kivy/pyjnius#284]
The unicode string encode/decode in pyjnius doesn't properly account for JNI's use of "modified" UTF-8: http://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html#wp16542 

This causes pyjnius to not properly handle supplementary unicode characters (i.e. four byte UTF-8 code points), which mangles string inputs to Java and throws UnicodeDecodeError when decoding Java string outputs. For example:

```python
from jnius import autoclass
Stack = autoclass('java.util.Stack')
String = autoclass('java.lang.String')

emoji = u'\U0001F602'

stack = Stack()
stack.push(emoji)
popped = stack.pop()
assert emoji == popped # FAIL

stack.push(String(emoji.encode('utf-8'), 'utf-8'))
popped = stack.pop() # (PY3) UnicodeDecodeError: 'utf-8' codec can't 
                     # decode byte 0xed in position 0: invalid continuation byte
```

The easiest fix is probably to pass strings through JNI's UTF-16 API (GetStringChars) instead of the modified UTF-8 API (GetStringUTFChars).

**Comment by g-bon** [comment]
@brandonherzog your fix on https://github.com/brandonherzog/pyjnius/tree/fix-unicode should solve #311  as well correct? Thanks for your effort
