### ISSUE TITLE
Not support unicode_literals ?

### ISSUE THREAD

**Issue by zhouyang209117** [kivy/pyjnius#311]
os version: win7 64bit
python version: 2.7.13
pyjnius version: 1.1.1
jdk version: 1.8.0_111
source code
```
# coding:utf-8
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
from jnius import autoclass

Stack = autoclass('java.util.Stack')
stack = Stack()
stack.push('hello')
stack.push('world')

print(stack.pop())
print(stack.pop())
```
The output is sth like this:
```
Y
ý
```
If delete this line,from __future__ import unicode_literals,  the output is right, that is
```
world
hello
```

**Comment by oddjobz** [comment]
Mm, your example works fine for me as-is .. (?)

**Comment by g-bon** [comment]
Happening to me as well. Seems to replicate the very first bug reported. #1

**Comment by Arnie97** [comment]
Confirmed this bug with both Python 2.7 and Python 3.6, any ideas?

**Comment by KeyWeeUsr** [comment]
Yup, duplicate.
