### ISSUE TITLE
DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AstroMen** [kivy/pyjnius#313]
When I use 'from jnius import autoclass', it appears import error as below.
Traceback (most recent call last):
  File "C:/XXX.py", line 3, in <module>
    from jnius import autoclass
  File "C:\...\Python27\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: %1 is not a valid Win32 application.

Cython (0.27.3)
jnius (1.1.0)
pyjnius (1.1.2.dev0)
Python 2.7 32bit

I have added "C:\Program Files\Java\jdk1.XXXX\jre\bin\server" to my Path of Windows environment.

Please help give any suggestion.
Thanks.

**Comment by AliPolat** [comment]
I got same error.

After I changed JAVA PATHs from **C:\Program Files....** to **C:\Program Files (x86)...** I succesfully imported jnius.

**Comment by Arnie97** [comment]
Seems to be caused by use 32-bit Python with 64-bit JDK (or vice versa).

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/pyjnius/issues/199#issuecomment-443013378 and https://github.com/kivy/pyjnius/issues/313#issuecomment-385369393.
