### ISSUE TITLE
jnius.JavaException: Class not found 'org/renpy/android/PythonActivity'

### ISSUE THREAD

**Issue by ignertic** [kivy/pyjnius#330]
Please help im trying to run my kivy app and i get this error

_root@SuperCode:/home/scode/Documents/kivy_gosh-master# python main.py
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_18-02-19_2.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-33aad99, 20180120
[INFO   ] [Python      ] v2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.2.4>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
\\ Peewee is Working ///////
\\ Peewee is Working ///////
[INFO   ] [Audio       ] Providers: audio_pygame (audio_ffpyplayer ignored)
 Traceback (most recent call last):
   File "main.py", line 18, in <module>
     from screens.sermons import *
   File "/home/scode/Documents/kivy_gosh-master/screens/sermons.py", line 22, in <module>
     PythonActivity = autoclass('org.renpy.android.PythonActivity')
   File "build/bdist.linux-i686/egg/jnius/reflect.py", line 158, in autoclass
   File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass
 jnius.JavaException: Class not found 'org/renpy/android/PythonActivity'_

**Comment by germn** [comment]
> autoclass('org.renpy.android.PythonActivity')

**1)** If you're not running app on Android you don't need to call this line.
Use condition to check OS:

```
from kivy.utils import platform

if platform == 'android':
   activity = autoclass('org.renpy.android.PythonActivity')
```

**2)** Even on Android it's outdated way to get activity. If you build apk with latest p4a version, you need to get activity with this code:

`activity = autoclass('org.kivy.android.PythonActivity')`

**Comment by Shirious** [comment]
How can I call that on terminal

**Comment by Shirious** [comment]
How can I call that on terminal ?

**Comment by ignertic** [comment]
Thank You for following up

:)
