### ISSUE TITLE
Segfault/NullPointerException using PythonJavaClass as proxy between Java and Python

### ISSUE THREAD

**Issue by kviktor** [kivy/pyjnius#332]
I created a class that implements one method of a built-in Java interface using PythonJavaClass. My class' constructor takes a function as the first argument and when the method I implemented is called it calls that function. After I initialize the class I simply pass it to my Activity instance and when I receive certain broadcasts I call the implemented method from Java to do the "callback" to Python. 

Using this method up to now these 3 things have happened
- the Activity segfaults
- the call throws a NullPointerException (I implemented a method that returns a boolean and the exception is about "cannot unbox null value to boolean" or something similar)
- things work flawlessly

One workaround I found was moving around the Python part of the code where I pass my class' instance to the Activity to different methods/functions. This fixed the issue however sometimes it creates DRY violations.

Has anyone experienced anything similar and came up with a more elegant solution?

**Comment by drmoose** [comment]
Does your `PythonJavaClass` subclass reliably call `super().__init__`? Because if not, the segfaulting could be #301, which is addressed by PR #299.

**Comment by kviktor** [comment]
I used that PR for my pyjnius build so I _think_ it calls the init.
