### ISSUE TITLE
Any news for 1.1.2?

### ISSUE THREAD

**Issue by stania** [kivy/pyjnius#342]
Many bugs are fixed after 1.1.1.

Unicode(#300) and Long problem(#233) are show-stopper.

Any news for 1.1.2?

**Comment by akshayaurora** [comment]
I think it is time we started letting CI automate minor releases every month, pyjnius in it's current state is very stable, least for automated minor releases

**Comment by jakirkham** [comment]
Could we get a tag for now at least? This alone would be very helpful.

For context, we need this for a conda package we are working on. ( https://github.com/conda-forge/staged-recipes/pull/6091 ) Also if you have any feedback on it, that would be appreciated as well.

cc @hanslovsky

**Comment by jakirkham** [comment]
Just checking in, is there a timeline for this?

**Comment by jsurloppe** [comment]
We have build problems with the current stable on pypi, the HEAD is working, can you make a release ? He would ease our deployment.

Thanks :)

**Comment by sanxore** [comment]
We have bugs with the current release (1.1.0) in pypi, and the HEAD work fine for us.
A release  would be very helpful.

Ty

**Comment by KeyWeeUsr** [comment]
[`1.1.2`](https://github.com/kivy/pyjnius/releases/tag/1.1.2) and [`1.1.3`](https://github.com/kivy/pyjnius/releases/tag/1.1.3) have been released. :)
