### ISSUE TITLE
PyJNIus available on conda forge now

### ISSUE THREAD

**Issue by hanslovsky** [kivy/pyjnius#348]
I had a `pyjnius` conda package on my personal channel (`hanslovsky`) for a while and now I was able to push it to `conda-forge` with the help of @jakirkham:
```
conda install -c conda-forge pyjnius
```

The package is built and linked against the OpenJDK that is available on conda-forge. It is available for Linux, Windows, and OSX. Currently, we distribute `1.1.2dev` as `1.1.1.post54`, which means 54 commits since the `1.1.1` tag. Once `1.1.2` is released (#342), we will create a `1.1.2` package on conda, as well.

**Comment by akshayaurora** [comment]
@hanslovsky thanks a ton! 💯

**Comment by KeyWeeUsr** [comment]
Link: https://github.com/conda-forge/pyjnius-feedstock, needs to be added to docs with the instructions for installation.
