### ISSUE TITLE
Make it possible to convert a python list to a Java array

### ISSUE THREAD

**Issue by ghost** [kivy/pyjnius#35]
There is an internal function to do this, but it not accessible in Python

**Comment by danyaljj** [comment]
It's been about 6 years since this question, so lots might have changed: 
I was looking for such functionality (i.e. converting python list to Java array), but didn't find anything in the documentation.

**Comment by danyaljj** [comment]
Found the functionality; would be super-helpful to add such examples to the documentation. 

```
>>> jArray = autoclass("java.lang.reflect.Array")
>>> a = jArray.newInstance(jString, 10)
>>> a
[None, None, None, None, None, None, None, None, None, None]
>>> a[0] = jString("nitish")
>>> a
[<java.lang.String at 0x103d619b0 jclass=java/lang/String jself=<LocalRef obj=0x7fc665f4a3f8 at 0x103abf190>>, None, None, None, None, None, None, None, None, None]
```

This wasn't trivial at all.

**Comment by emclab** [comment]
Any pyinius function available to convert a python lis to java byte[]? I am looking for one to generate new initialization vector (iv) for cipher.init() in kivy android app.

**Comment by cmacdonald** [comment]
Cant you just use the `bytes()` cast? Ie `bytes([1,2])`
