### ISSUE TITLE
"from jnius import autoclass" at Python Shell causes the following error message, "undefined symbol: PyFPE_jbuf".

### ISSUE THREAD

**Issue by fbaldris** [kivy/pyjnius#353]
If I use the Python Shell (Python 2.7.15rc1 Shell) to import autoclass from jnius the following error message rises,

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> from jnius import autoclass

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from jnius import autoclass
  File "/usr/local/lib/python2.7/dist-packages/jnius/__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: /usr/local/lib/python2.7/dist-packages/jnius/jnius.so: undefined symbol: PyFPE_jbuf
>>>

Versions,

Python 2.7.15rc1
Pyjnius version 1.1.1
Ubuntu 18.04.1

Please, can you help me ?

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/numpy/numpy/issues/8415#issuecomment-269103493, try to install to a Python that has been compiled with `--with-fpectl`. I'm not quite sure, but I think that this:

```bash
[GCC 7.3.0] on linux2
Type "copyright", "credits" or "license()" for more information.
```

actually means a custom built CPython, therefore it'd be useful to check what flags the custom build used and try to add `--with-fpectl`. Still though, nothing to do *directly* with PyJNIus.
