### ISSUE TITLE
Add appveyor.yml to make sure PyJNIus works properly on Windows

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/pyjnius#365]
This might be a little bit tricky since I'm not sure how difficult it might be to download `.exe`s for JDK, but the compilation itself + running the tests is quite easy and for me it was enough to just add `JAVA_HOME=C:\Program Files (x86)\Java\...\bin` as a path to JDK `bin` folder. There is a bug though if the variable is set up with quotes because the `setup.py` doesn't handle them and the path itself is then crippled.

Ref: #352

**Comment by hadim** [comment]
For JDK, I would suggest you use the ones provided with conda forge: https://github.com/Anaconda-Platform/anaconda-project/blob/master/appveyor.yml

Also, note that windows is available on Windows: https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by KeyWeeUsr** [comment]
Closed by #370.
