### ISSUE TITLE
Using python keywords to access java methods in Jnius? (support)

### ISSUE THREAD

**Issue by fr3nzy** [kivy/pyjnius#382]
Unfortunately, I don't know Java, so I don't know of any way to work around this
In the process of creating a notification, one creates a notification manager in order to open a previously defined notification. This is the java syntax:

`NotificationManagerCompat notificationManager = NotificationManagerCompat.from(this);`
From the documentation:

> To use this class, call the static function `from(Context)` to get a `NotificationManagerCompat `object, and then call one of its methods to post or cancel notifications.

The relevant python would be:

```
CurrentActivity  = autoclass('org.kivy.android.PythonActivity').mActivity
activityContext = CurrentActivity.this

NotificationManager = autoclass('android.support.v4.app.NotificationManagerCompat')
notificationManager = NotificationManwager.from(acitivtyContext)
```

As expected, this gives a syntax error regarding from. Is there any way to work around this? I'm clueless here :(

**Comment by AbdealiJK** [comment]
```
In [22]: getattr(arraylist, "add")
Out[22]: <jnius.JavaMultipleMethod at 0x10c0c1ac8>

In [23]: arraylist.add
Out[23]: <jnius.JavaMultipleMethod at 0x10c0c1ac8>
```
