### ISSUE TITLE
How to access android package? [support]

### ISSUE THREAD

**Issue by fr3nzy** [kivy/pyjnius#383]
I am not very familiar with Java, but it appears that Java packages are different to classes, being a namespace or a group, wherein classes may be present. How does one go about accessing such in pyjnius? Using `package.class` through autoclass does not work as java does not recognize it as a class. 

Example - ` android.support.v4.app.NotificationCompat` - `android.support.v4.app` is a package not a class, but `NotificationCompat` is a class. I'm not sure how to go about letting jnius know of this and I can't find any info in the documentation. 

Please lend a hand :)

**Comment by KeyWeeUsr** [comment]
You are using Oreo, aren't you? Check this PR https://github.com/kivy/plyer/pull/492 it already has the new notifications covered :)

About accessing the packages, well, there can be only [one public class](https://stackoverflow.com/a/48977770/5994041) and you can access it the normal way, but I don't think you can access the package itself like in Python. At least not according to [this answer](https://stackoverflow.com/a/12249038/5994041).

**Comment by fr3nzy** [comment]
@KeyWeeUsr I will look into that thanks, the reason I am using android classes rather than plyer is for increased notification functionality. I am right in presuming that the what is present in the `plyer.facades.notify`  https://plyer.readthedocs.io/en/latest/#plyer.facades.Notification is all the functionality that is available?
