### ISSUE TITLE
Error Importing From Any JAVA_HOME path 

### ISSUE THREAD

**Issue by murphy214** [kivy/pyjnius#384]
Hey just figured I'd post an issue I was having with importing as it looks like this project is being actively maintained. I tried several different JAVA_HOME directories all of which I'm pretty sure were correct (for example ```/usr/lib/jvm/java-8-openjdk-amd64/``` is the current JAVA_HOME environmental variable. The highest JAVA_VERSION I have is 11 which also failed with the same error messages. I tried all the other available Java versions installed and did some googling and couldn't find much.

I'm running Ubuntu 18.4.1 Ubuntu 18.04.1 with a Threadripper CPU although that probably isn't the issue I figure it is probably the unique thing about my environment. 

Error Message:
```
 Traceback (most recent call last):
   File "here.py", line 15, in <module>
     import jnius
   File "/home/bennett/anaconda2/lib/python2.7/site-packages/jnius/__init__.py", line 13, in <module>
     from .reflect import *  # noqa
   File "/home/bennett/anaconda2/lib/python2.7/site-packages/jnius/reflect.py", line 15, in <module>
     class Class(with_metaclass(MetaJavaClass, JavaClass)):
   File "/home/bennett/.local/lib/python2.7/site-packages/six.py", line 827, in __new__
     return meta(name, bases, d)
   File "jnius/jnius_export_class.pxi", line 111, in jnius.MetaJavaClass.__new__
   File "jnius/jnius_export_class.pxi", line 161, in jnius.MetaJavaClass.resolve_class
   File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
 SystemError: Error calling dlopen(/usr/lib/jvm/java-8-openjdk-amd64/lib/server/libjvm.so: /usr/lib/jvm/java-8-openjdk-amd64/lib/server/libjvm.so: cannot open shared object file: No such file or directory
```

**Comment by AKuederle** [comment]
Have a look if the files jinius is looking for actually exist. For some reason the folder structure inside the Java folder can be different, depending on how you installed Java.

**Comment by Zen-CODE** [comment]
Please post the exact output of this command:

    update-java-alternatives --list

Then post the exact output of:

    printenv | grep JAVA_HOME

We just need to verify exactly what these are. Then perhaps a 

    cat /usr/lib/jvm/java-8-openjdk-amd64/lib/server/libjvm.so

to see if the file is actually there.

**Comment by qbx2** [comment]
Why not just find libjvm recursively in JAVA_HOME?

libjvm path on my system is wrong, too.
The system is MacOS X Mojave with JDK SE 8 (latest)

SystemError: Error calling dlopen(b'/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/lib/server/libjvm.dylib': b'dlopen(/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/lib/server/libjvm.dylib, 10): image not found'

The correct path is:
/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home//jre/lib/server/libjvm.dylib

**Comment by Zen-CODE** [comment]
I think this issue has been addressed sufficiently and, as the original author is not responding, shall close it.
