### ISSUE TITLE
Sending None/null in an argument of type Object

### ISSUE THREAD

**Issue by AbdealiJK** [kivy/pyjnius#385]
I'm trying to call a function which has the signature:
```java
	 * @param value The input value in user-supplied representation.
	 * Use <code>null</code> to represent a missing input value.
	 */
	public FieldValue prepare(Object value){
		return ...
	}
```

To call it, when I do:
```
.prepare(600)
```
It throws an error: `JavaException: Invalid python object for this argument. Want 'java/lang/Object', got 600`

Is there any helper function I can use to convert my python variable to a Object?

For a temp workaround I needed to use `float`, `str`, `None`. So ... I tried:
```python
if isinstance(val, float):
    val = jnius.autoclass('java.lang.Double')(val)
elif isinstance(val, str):
    val = jnius.autoclass('java.lang.String')(val)
else:
    raise NotImplementedError("Unknown type: {}".format(type(val))
```

But I couldn't figure how to send `None` to this function which seems to support only `Object` as the argument.
The function does support `null` as a valid input. Unsure how to send it from jnius though.

**Comment by KeyWeeUsr** [comment]
Fixed by #386.
