### ISSUE TITLE
I can't print non-ASCII strings

### ISSUE THREAD

**Issue by NDelt** [kivy/pyjnius#389]
code:
```
# coding=utf-8
from jnius import autoclass
autoclass("java.lang.System").out.println("안녕 World!")
```
output:
```
�ȳ�
```

If I try to print non-ASCII text(above is Korean), broken text is displayed.
Is it impossible to process Unicode encoding with PyJnius?

**Comment by KeyWeeUsr** [comment]
I think you either might have saved the file with bad encoding or your console doesn't print the characters properly. PyJNIus can handle unicode fine, however to be sure, try to save those characters to a file with appropriate encodings and check if you get the same output. I don't have such fonts, therefore it doesn't display properly in my console.
