### ISSUE TITLE
Can't insatll Pyjnius/jnius 

### ISSUE THREAD

**Issue by nutchynicha** [kivy/pyjnius#390]
I try to follow the installation but it's not work. 
I got this error:

Collecting pyjnius

  Using cached https://files.pythonhosted.org/packages/da/c3/5e65aa78108811ad003a70c364f20964af7d5734785f2d4b71b199c84c6c/pyjnius-1.1.4.tar.gz

Requirement already satisfied: six>=1.7.0 in c:\python27\lib\site-packages (from pyjnius) (1.12.0)

Requirement already satisfied: cython in c:\python27\lib\site-packages (from pyjnius) (0.29.3)

Building wheels for collected packages: pyjnius

  Running setup.py bdist_wheel for pyjnius ... error

  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\macint~1\\appdata\\local\\temp\\pip-install-oj4jhf\\pyjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\macint~1\appdata\local\temp\pip-wheel-ur3m2b --python-tag cp27:

  C:\Program Files\Java\jdk1.8.0_202

  WARNING: Not able to assign machine() = AMD64 to a cpu value!

           Using cpu = 'i386' instead!

  JDK_HOME: C:\Program Files\Java\jdk1.8.0_202

  JRE_HOME: C:\Program Files\Java\jdk1.8.0_202\jre

  warning: [options] bootstrap class path not set in conjunction with -source 1.6

  1 warning

  running bdist_wheel

  running build

  running build_py

  creating build

  creating build\lib.win32-2.7

  copying jnius_config.py -> build\lib.win32-2.7

  creating build\lib.win32-2.7\jnius

  copying jnius\reflect.py -> build\lib.win32-2.7\jnius

  copying jnius\signatures.py -> build\lib.win32-2.7\jnius

  copying jnius\__init__.py -> build\lib.win32-2.7\jnius

  creating build\lib.win32-2.7\jnius\src

  creating build\lib.win32-2.7\jnius\src\org

  creating build\lib.win32-2.7\jnius\src\org\jnius

  copying jnius\src\org\jnius\NativeInvocationHandler.class -> build\lib.win32-2.7\jnius\src\org\jnius

  copying jnius\src\org\jnius\NativeInvocationHandler.java -> build\lib.win32-2.7\jnius\src\org\jnius

  running build_ext

  cythoning jnius\jnius.pyx to jnius\jnius.c

  c:\python27\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: c:\users\macint~1\appdata\local\temp\pip-install-oj4jhf\pyjnius\jnius\jnius.pyx

    tree = Parsing.p_module(s, pxd, full_module_name)

  warning: jnius\jnius.pyx:2:0: __getslice__, __setslice__, and __delslice__ are not supported by Python 3, use __getitem__, __setitem__, and __delitem__ instead

  building 'jnius' extension

  creating build\temp.win32-2.7

  creating build\temp.win32-2.7\Release

  creating build\temp.win32-2.7\Release\jnius

  C:\Users\Macintosh HD\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Java\jdk1.8.0_202\include" "-IC:\Program Files\Java\jdk1.8.0_202\include\win32" -Ic:\python27\include -Ic:\python27\PC /Tcjnius\jnius.c /Fobuild\temp.win32-2.7\Release\jnius\jnius.obj

  jnius.c

  jnius\jnius.c(3962) : warning C4047: 'function' : 'void **' differs in levels of indirection from 'JNIEnv **'

  jnius\jnius.c(3962) : warning C4022: 'function through pointer' : pointer mismatch for actual parameter 2

  jnius\jnius.c(8647) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

  jnius\jnius.c(10720) : warning C4090: '=' : different 'const' qualifiers

  jnius\jnius.c(13215) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

  jnius\jnius.c(14098) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

  jnius\jnius.c(20347) : warning C4047: '=' : 'jobject' differs in levels of indirection from 'jobject *'

  jnius\jnius.c(20356) : warning C4047: '=' : 'jobject' differs in levels of indirection from 'jclass *'

  jnius\jnius.c(35032) : warning C4090: '=' : different 'const' qualifiers

  jnius\jnius.c(35041) : warning C4090: '=' : different 'const' qualifiers

  C:\Users\Macintosh HD\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_202\lib" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_202\bin\server" /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild /LIBPATH:c:\python27\PC\VS9.0 jvm.lib /EXPORT:initjnius build\temp.win32-2.7\Release\jnius\jnius.obj /OUT:build\lib.win32-2.7\jnius\jnius.pyd /IMPLIB:build\temp.win32-2.7\Release\jnius\jnius.lib /MANIFESTFILE:build\temp.win32-2.7\Release\jnius\jnius.pyd.manifest

     Creating library build\temp.win32-2.7\Release\jnius\jnius.lib and object build\temp.win32-2.7\Release\jnius\jnius.exp

  jnius.obj : error LNK2019: unresolved external symbol __imp__JNI_CreateJavaVM@12 referenced in function ___pyx_f_5jnius_create_jnienv

  build\lib.win32-2.7\jnius\jnius.pyd : fatal error LNK1120: 1 unresolved externals

  error: command 'C:\\Users\\Macintosh HD\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

  ----------------------------------------

  Failed building wheel for pyjnius

  Running setup.py clean for pyjnius

Failed to build pyjnius

Installing collected packages: pyjnius

  Running setup.py install for pyjnius ... error

    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\macint~1\\appdata\\local\\temp\\pip-install-oj4jhf\\pyjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\macint~1\appdata\local\temp\pip-record-zmle0p\install-record.txt --single-version-externally-managed --compile:

    C:\Program Files\Java\jdk1.8.0_202

    WARNING: Not able to assign machine() = AMD64 to a cpu value!

             Using cpu = 'i386' instead!

    JDK_HOME: C:\Program Files\Java\jdk1.8.0_202

    JRE_HOME: C:\Program Files\Java\jdk1.8.0_202\jre

    warning: [options] bootstrap class path not set in conjunction with -source 1.6

    1 warning

    running install

    running build

    running build_py

    creating build

    creating build\lib.win32-2.7

    copying jnius_config.py -> build\lib.win32-2.7

    creating build\lib.win32-2.7\jnius

    copying jnius\reflect.py -> build\lib.win32-2.7\jnius

    copying jnius\signatures.py -> build\lib.win32-2.7\jnius

    copying jnius\__init__.py -> build\lib.win32-2.7\jnius

    creating build\lib.win32-2.7\jnius\src

    creating build\lib.win32-2.7\jnius\src\org

    creating build\lib.win32-2.7\jnius\src\org\jnius

    copying jnius\src\org\jnius\NativeInvocationHandler.class -> build\lib.win32-2.7\jnius\src\org\jnius

    copying jnius\src\org\jnius\NativeInvocationHandler.java -> build\lib.win32-2.7\jnius\src\org\jnius

    running build_ext

    skipping 'jnius\jnius.c' Cython extension (up-to-date)

    building 'jnius' extension

    creating build\temp.win32-2.7

    creating build\temp.win32-2.7\Release

    creating build\temp.win32-2.7\Release\jnius

    C:\Users\Macintosh HD\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Java\jdk1.8.0_202\include" "-IC:\Program Files\Java\jdk1.8.0_202\include\win32" -Ic:\python27\include -Ic:\python27\PC /Tcjnius\jnius.c /Fobuild\temp.win32-2.7\Release\jnius\jnius.obj

    jnius.c

    jnius\jnius.c(3962) : warning C4047: 'function' : 'void **' differs in levels of indirection from 'JNIEnv **'

    jnius\jnius.c(3962) : warning C4022: 'function through pointer' : pointer mismatch for actual parameter 2

    jnius\jnius.c(8647) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

    jnius\jnius.c(10720) : warning C4090: '=' : different 'const' qualifiers

    jnius\jnius.c(13215) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

    jnius\jnius.c(14098) : warning C4244: '=' : conversion from 'long' to 'jchar', possible loss of data

    jnius\jnius.c(20347) : warning C4047: '=' : 'jobject' differs in levels of indirection from 'jobject *'

    jnius\jnius.c(20356) : warning C4047: '=' : 'jobject' differs in levels of indirection from 'jclass *'

    jnius\jnius.c(35032) : warning C4090: '=' : different 'const' qualifiers

    jnius\jnius.c(35041) : warning C4090: '=' : different 'const' qualifiers

    C:\Users\Macintosh HD\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_202\lib" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_202\bin\server" /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild /LIBPATH:c:\python27\PC\VS9.0 jvm.lib /EXPORT:initjnius build\temp.win32-2.7\Release\jnius\jnius.obj /OUT:build\lib.win32-2.7\jnius\jnius.pyd /IMPLIB:build\temp.win32-2.7\Release\jnius\jnius.lib /MANIFESTFILE:build\temp.win32-2.7\Release\jnius\jnius.pyd.manifest

       Creating library build\temp.win32-2.7\Release\jnius\jnius.lib and object build\temp.win32-2.7\Release\jnius\jnius.exp

    jnius.obj : error LNK2019: unresolved external symbol __imp__JNI_CreateJavaVM@12 referenced in function ___pyx_f_5jnius_create_jnienv

    build\lib.win32-2.7\jnius\jnius.pyd : fatal error LNK1120: 1 unresolved externals

    error: command 'C:\\Users\\Macintosh HD\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

    ----------------------------------------

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\macint~1\\appdata\\local\\temp\\pip-install-oj4jhf\\pyjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\macint~1\appdata\local\temp\pip-record-zmle0p\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\macint~1\appdata\local\temp\pip-install-oj4jhf\pyjnius\

**Comment by KeyWeeUsr** [comment]
Your Python version seems to be 32bit and your Java version is 64bit, so I don't think it'll work this way for you. Try to either install 64bit Python or 32bit JDK.
