### ISSUE TITLE
Installation error windows 10 (64 bit).

### ISSUE THREAD

**Issue by dusadvarshit** [kivy/pyjnius#416]
Hi, I am trying to install pyjnius on Windows 10 (64 bit). To my best of knowledge, I have followed all the instructions possible.
1. I installed the necessary dependencies such as Cython.
2. I installed the python development dependencies from Visual studio 2017.
3. I set up a JAVA_HOME environment pointing to my jdk directory and also added JRE to my path variables.
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0_191\bin
      Path: C:\Program Files\Java\jre1.8.0_191\bin\server
4. I tried installing pyjnius using pip.
5. **In my base python environment it fails to load** and gives me following error.

  _C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files\Java\jdk1.8.0_191\include" "-IC:\Program Files\Java\jdk1.8.0_191\include\win32" -Ic:\users\dusad\anaconda1\anaconda3\include -Ic:\users\dusad\anaconda1\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" /Tcjnius\jnius.c /Fobuild\temp.win-amd64-3.5\Release\jnius\jnius.obj
    jnius.c
    jnius\jnius.c(1942): warning C4273: 'JNI_CreateJavaVM': inconsistent dll linkage
    C:\Program Files\Java\jdk1.8.0_191\include\jni.h(1938): note: see previous definition of 'JNI_CreateJavaVM'
    jnius\jnius.c(3359): warning C4244: '=': conversion from 'Py_ssize_t' to 'jint', possible loss of data
    jnius\jnius.c(3619): warning C4047: 'function': 'void **' differs in levels of indirection from 'JNIEnv **'
    jnius\jnius.c(3619): warning C4022: 'function through pointer': pointer mismatch for actual parameter 2
    jnius\jnius.c(6038): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    jnius\jnius.c(6048): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    jnius\jnius.c(8398): warning C4244: '=': conversion from 'long' to 'jchar', possible loss of data
    jnius\jnius.c(10589): warning C4090: '=': different 'const' qualifiers
    jnius\jnius.c(12726): warning C4244: 'function': conversion from 'Py_ssize_t' to 'jsize', possible loss of data
    jnius\jnius.c(13179): warning C4244: '=': conversion from 'long' to 'jchar', possible loss of data
    jnius\jnius.c(13395): warning C4267: '=': conversion from 'size_t' to 'jsize', possible loss of data
    jnius\jnius.c(13554): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    jnius\jnius.c(14010): warning C4244: '=': conversion from 'long' to 'jchar', possible loss of data
    jnius\jnius.c(15365): warning C4311: 'type cast': pointer truncation from 'void *' to 'long'
    jnius\jnius.c(19835): warning C4047: '=': 'jobject' differs in levels of indirection from 'jobject *'
    jnius\jnius.c(19844): warning C4047: '=': 'jobject' differs in levels of indirection from 'jclass *'
    jnius\jnius.c(27069): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    jnius\jnius.c(30844): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    jnius\jnius.c(34691): warning C4090: '=': different 'const' qualifiers
    jnius\jnius.c(34700): warning C4090: '=': different 'const' qualifiers
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_191\lib" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_191\bin\server" /LIBPATH:c:\users\dusad\anaconda1\anaconda3\libs /LIBPATH:c:\users\dusad\anaconda1\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64" jvm.lib /EXPORT:PyInit_jnius build\temp.win-amd64-3.5\Release\jnius\jnius.obj /OUT:build\lib.win-amd64-3.5\jnius\jnius.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\jnius\jnius.cp35-win_amd64.lib
    jnius.obj : warning LNK4197: export 'PyInit_jnius' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\jnius\jnius.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\jnius\jnius.cp35-win_amd64.exp
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "c:\users\dusad\anaconda1\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dusad\\AppData\\Local\\Temp\\pip-install-bthcezvv\\pyjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dusad\AppData\Local\Temp\pip-record-34nxz6pw\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\dusad\AppData\Local\Temp\pip-install-bthcezvv\pyjnius\_

6. In my additional python environment (where I intend to use it) it installs but fails to be imported with the following error:

_\Anaconda1\Anaconda3\envs\py_anjana\lib\site-packages\jnius\__init__.py in <module>
     10 __version__ = '1.2.0'
     11 
---> 12 from .jnius import *  # noqa
     13 from .reflect import *  # noqa
     14 from six import with_metaclass

ImportError: DLL load failed: The specified module could not be found._

Please advice me on how to install it. Installation using Conda failed as well. Is it because of my JDK environment. Do I need to explicitly install OpenJDK to make it work? 

Thank you!
Warm regards
Varshit

**Comment by Csega** [comment]
Same problem here. Previous versions worked fine.

**Comment by Csega** [comment]
I found a solution. It appears, that every dll referenced in the jnius.cp37-win_amd64.pyd file (bytecode, you can check the dlls it tries to load, the end of the filename of course can change based on your exact python version) should be in the path! This wasn't the case before, but right now (as of pyjnius version 1.2.0) the following dlls should be available through the path:

1. jvm.dll
2. kernel32.dll
3. vcruntime140.dll
4. python37.dll (or whatever python 3 version you use)
5. api-ms-win-crt-stdio-l1-1-0.dll
6. api-ms-win-crt-heap-l1-1-0.dll
7. api-ms-win-crt-runtime-l1-1-0.dll

If you use powershell, you can easily check the availability of these files using a simple (and a bit ugly, but nevertheless, working) script:

foreach ($DLL in @("jvm.dll","vcruntime140.dll","kernel32.dll", "python37.dll","api-ms-win-crt-stdio-l1-1-0.dll","api-ms-win-crt-heap-l1-1-0.dll","api-ms-win-crt-runtime-l1-1-0.dll")) { $I = 0; foreach ($Entry in (Get-Content Env:/PATH).Split(';')) { if (Join-Path -Path $Entry -ChildPath $DLL | Test-Path) { $I +=1; } } if ($I -eq 0) {throw "$DLL not found in PATH"} }

If it gives an error, a dll from the path is missing (prints the exact dll name out). You just have to add everything, what's missing to the path, and voilá: Pyjnius will work again. (At least it did for me.)

**Comment by dusadvarshit** [comment]
Thank you Csega! I will follow-up and see if it works for me.

**Comment by tshirtman** [comment]
this should be fixed in latest version, please comment so we reopen, or open a new issue, if that's not the case, thanks.

**Comment by MariwanJ** [comment]
Still I am not able to install the library on Windows. 
If you don't have JRE installed .. it fails. 
the following peace of code will never work on Windows. 
` jre_home = None
    if exists(join(jdk_home, 'jre')):
        jre_home = join(jdk_home, 'jre')
    if not jre_home:
        jre_home = subprocess.Popen(
            'readlink -f `which java` | sed "s:bin/java::"',
            shell=True, stdout=subprocess.PIPE).communicate()[0].strip()
    if not jre_home:
        raise Exception('Unable to determine JRE_HOME')`

**Comment by cmacdonald** [comment]
That line code isnt in Jnius 1.4, right?

**Comment by MariwanJ** [comment]
jnius-1.1.0.tar
And the solution for windows is to install pyjnius not jnius

**Comment by cmacdonald** [comment]
jnius-1.1.0 is very old...

**Comment by MariwanJ** [comment]
I don't know why I got that when I did pip3 install jnius.. thanks anyway

**Comment by cmacdonald** [comment]
@tshirtman can we release something under the jnius namespace that directs people to pyjnius?

**Comment by MariwanJ** [comment]
And I couldn't use the library under windows. Since I am trying to use bluetooth and the JAVA classes are available only on Android. Don't know a solution. thanks anyway.

**Comment by tshirtman** [comment]
> @tshirtman can we release something under the jnius namespace that directs people to pyjnius?

We could, i still have access to that project, i could add you as a collaborator if you have a pypi account and want to look into, it, not sure exactly what to do about it otherwise, maybe better not to release an updated version, but we could maybe release a package that doesn’t install, with a clear error, and an updated readme to point to the new project?

**Comment by cmacdonald** [comment]
Something like that. I'll try to find another deprecated package that does likewise that can inspire us.
