### ISSUE TITLE
Installation error source and target option

### ISSUE THREAD

**Issue by sioschul** [kivy/pyjnius#418]
I have installed JDK 12.0.1, Python 3.7, Visual Studius C++ Compiler and Cython.
I tried installing Pyjnius with the command pip install pyjnius and get the following error:

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    C:\Program Files\Java\jdk-12.0.1\bin
    WARNING: Not able to assign machine() = AMD64 to a cpu value!
             Using cpu = 'i386' instead!
    JDK_HOME: C:\Program Files\Java\jdk-12.0.1

    JRE_HOME: None

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Acer\AppData\Local\Temp\pip-install-rgkf0yzv\pyjnius\setup.py", line 246, in <module>
        compile_native_invocation_handler(JDK_HOME, JRE_HOME)
      File "C:\Users\Acer\AppData\Local\Temp\pip-install-rgkf0yzv\pyjnius\setup.py", line 96, in compile_native_invocation_handler
        join('jnius', 'src', 'org', 'jnius', 'NativeInvocationHandler.java')
      File "c:\users\acer\appdata\local\programs\python\python37-32\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk-12.0.1\\bin\\javac.exe', '-target', '1.6', '-source', '1.6', 'jnius\\src\\org\\jnius\\NativeInvocationHandler.java']' returned non-zero exit status 2.
    ----------------------------------------
    ERROR: Command "python setup.py egg_info" failed with error code 1 in 
    C:\Users\Acer\AppData\Local\Temp\pip-install-rgkf0yzv\pyjnius\
The problem seem to be the specified versions in the javac call.
Anyone here who knows how to fix this or how to work around?

Thanks already.

**Comment by jrnp97** [comment]
I had the same error and actual version of pip installer broken when JAVA_HOME directory has a `space` on window installation, how i explain on (https://github.com/kivy/pyjnius/pull/420) then if you want use I recommend move your JAVA_HOME directory to one path without space. 

PD: JDK version 12.0.1 not support -source 1.6 and target 1.6, I used 11.0.3 instead.

**Comment by sioschul** [comment]
Thanks for replying. I moved my Java installation to a path without space, and updated JAVA_HOME as well as PATH. I am still getting the same error however.

**Comment by jrnp97** [comment]
Hello, do you change JAVA version ?

> PD: JDK version 12.0.1 not support -source 1.6 and target 1.6, I used 11.0.3 instead.

**Comment by tshirtman** [comment]
we now target source level 1.7, so this shouldn't be an issue anymore.
