### ISSUE TITLE
Install error w/ JDK 12

### ISSUE THREAD

**Issue by nearbydelta** [kivy/pyjnius#421]
Hi. Thanks for maintaining very useful library.

I'm using pyjnius 1.2.0 with Windows 10 / Ubuntu 16.04.
After I installed JDK 12 on my machine, installation of pyjnius keeps fail with following error message:

> ERROR: Complete output from command python setup.py egg_info:
> ERROR: warning: [options] bootstrap class path not set in conjunction with -source 6
> error: Source option 6 is no longer supported. Use 7 or later.
> error: Target option 6 is no longer supported. Use 7 or later.

It seems that support of JAVA 6 is deprecated on JDK 12.
I have two questions:

1. Is it fine to modify source/target options in Makefile?
2. If it is fine, then could you modify the options?

**Comment by kibernick** [comment]
Can confirm that I am also having this issue on a Mac.

**Comment by geisterfurz007** [comment]
Duplicate of #418; just for documentation and stuff.

**Comment by Sn3akyP3t3** [comment]
This maximum version detail should appear in the install documentation as well.  I fell for this one as well.

**Comment by tshirtman** [comment]
This should be ok now, as the CI now builds from java 8 to java 12 without issues.
