### ISSUE TITLE
Camera Access

### ISSUE THREAD

**Issue by AntoniRomera** [kivy/pyjnius#426]
`
file:///sdcard/172019_125005.jpg` exposed beyond app through ClipData.Item.getUri()
`

I got this error when trying to access the camera, someone knows how to fix it?

**Comment by tshirtman** [comment]
I got the same issue and started experimenting with solutions, but i don't have a working one yet https://gist.github.com/tshirtman/4bf8fdf745eb4a961b0f83066fe6a8d3
