### ISSUE TITLE
Tests don't pass (doesn't find libraries)

### ISSUE THREAD

**Issue by hanke** [kivy/pyjnius#43]
Hi,

I'm trying to run pyjnius on Debian wheezy. The vast majority of the tests (make tests) fails. It seems to be (mostly) related to the fact that it doesn't find the jars required for the tests. The failure looks like this:

    ======================================================================
    ERROR: test_instance_methods (test_basics.BasicsTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/michael/hacking/testkraut/db/pyjnius/tests/test_basics.py", line 31, inn test_instance_methods
        test = autoclass('org.jnius.BasicsTest')()
      File "/home/michael/hacking/testkraut/db/pyjnius/jnius/reflect.py", line 109, in autoclass
        c = find_javaclass(clsname)
      File "jnius_export_func.pxi", line 23, in jnius.find_javaclass (jnius/jnius.c:7418)
    JavaException: Class not found 'org/jnius/BasicsTest'

I can work with the standard library without problems:

    >>> from jnius import autoclass
    >>> autoclass('java.lang.System').out.println('Hello world')
    Hello world

but accessing any other JAR fails.

I tried Debian's openjdk 6 and 7 -- the result is the same. It there any (versioned) dependency that I am missing?

**Comment by dessant** [comment]
Fixed in master.
