### ISSUE TITLE
Errore calling dlopen Ubuntu 

### ISSUE THREAD

**Issue by BooHan** [kivy/pyjnius#430]
Have this problem.
Java_home is in the right place, but it search for java 1.7 , why? what is this? 

FullLog:
generico@generico-System-Product-Name:~/Scrivania/app6$ /bin/python3 /home/generico/Scrivania/app6/main.py
[INFO   ] [Logger      ] Record log in /home/generico/.kivy/logs/kivy_19-07-03_30.txt
INFO:kivy:[Logger      ] Record log in /home/generico/.kivy/logs/kivy_19-07-03_30.txt
[INFO   ] [Kivy        ] v1.11.1
INFO:kivy:[Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.7/dist-packages/kivy/__init__.py"
INFO:kivy:[Kivy        ] Installed at "/usr/local/lib/python3.7/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
INFO:kivy:[Python      ] v3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/bin/python3"
INFO:kivy:[Python      ] Interpreter at "/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
INFO:kivy:[Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
INFO:kivy:[Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
INFO:kivy:[Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
INFO:kivy:[Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
INFO:kivy:[GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
INFO:kivy:[GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.1 Mesa 19.0.2'>
INFO:kivy:[GL          ] OpenGL version <b'3.1 Mesa 19.0.2'>
[INFO   ] [GL          ] OpenGL vendor <b'X.Org'>
INFO:kivy:[GL          ] OpenGL vendor <b'X.Org'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD SUMO2 (DRM 2.50.0 / 5.0.0-20-generic, LLVM 8.0.0)'>
INFO:kivy:[GL          ] OpenGL renderer <b'AMD SUMO2 (DRM 2.50.0 / 5.0.0-20-generic, LLVM 8.0.0)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
INFO:kivy:[GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40'>
INFO:kivy:[GL          ] Shading version <b'1.40'>
[INFO   ] [GL          ] Texture max size <16384>
INFO:kivy:[GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
INFO:kivy:[GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
INFO:kivy:[Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
INFO:kivy:[Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/home/generico/Scrivania/app6/main.py", line 18, in <module>
WARNING:kivy:stderr:   File "/home/generico/Scrivania/app6/main.py", line 18, in <module>
     from jnius import autoclass
WARNING:kivy:stderr:     from jnius import autoclass
   File "/usr/local/lib/python3.7/dist-packages/jnius/__init__.py", line 13, in <module>
WARNING:kivy:stderr:   File "/usr/local/lib/python3.7/dist-packages/jnius/__init__.py", line 13, in <module>
     from .reflect import *  # noqa
WARNING:kivy:stderr:     from .reflect import *  # noqa
   File "/usr/local/lib/python3.7/dist-packages/jnius/reflect.py", line 14, in <module>
WARNING:kivy:stderr:   File "/usr/local/lib/python3.7/dist-packages/jnius/reflect.py", line 14, in <module>
     class Class(with_metaclass(MetaJavaClass, JavaClass)):
WARNING:kivy:stderr:     class Class(with_metaclass(MetaJavaClass, JavaClass)):
   File "/usr/lib/python3/dist-packages/six.py", line 827, in __new__
WARNING:kivy:stderr:   File "/usr/lib/python3/dist-packages/six.py", line 827, in __new__
     return meta(name, bases, d)
WARNING:kivy:stderr:     return meta(name, bases, d)
   File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
WARNING:kivy:stderr:   File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
   File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
WARNING:kivy:stderr:   File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
   File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
WARNING:kivy:stderr:   File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
WARNING:kivy:stderr:   File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
WARNING:kivy:stderr:   File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
 SystemError: Error calling dlopen(b'/usr/lib/jvm/jdk1.7.0/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/jdk1.7.0/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'
WARNING:kivy:stderr: SystemError: Error calling dlopen(b'/usr/lib/jvm/jdk1.7.0/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/jdk1.7.0/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'

**Comment by tshirtman** [comment]
Can you try with latest version? looking up the jvm library has been made a bit clearer.

**Comment by Julian-O** [comment]
No reply after 3+ years. Closing as stale.
