### ISSUE TITLE
Adding cython to pyjnius' `requires_dist`

### ISSUE THREAD

**Issue by srvxid** [kivy/pyjnius#433]
I'm trying to automate my build process using Poetry, and include `pyjnius` as a dependency. However, since cython is not listed as a required distr in https://pypi.org/pypi/pyjnius/json, it isn't detected as an auto imported package.

Basically imitating a pre-install of Cython (with pip) in an automated build system is a non-trivial step as most dependency resolvers start with the innermost dependency and cython isn't even listed as one. Wouldn't it be much easier if cython is listed as a setup_requires dependency so build automation tools work well with pyjnius ?

**Comment by AbdealiJK** [comment]
This is done now in https://github.com/kivy/pyjnius/pull/417

**Comment by srvxid** [comment]
@AbdealiJK That was great work, thanks!
