### ISSUE TITLE
Make and publish a 1.2.1 release to PyPI

### ISSUE THREAD

**Issue by vruusmann** [kivy/pyjnius#439]
I've been waiting for an official release that included the following change: https://github.com/kivy/pyjnius/commit/6553ad4409782fd1c37247c64736f4aa698a00b2

It's been six months already.

**Comment by AbdealiJK** [comment]
Pretty much the case for me too - Is there a plan to make a release any time soon ?

**Comment by cmacdonald** [comment]
A bump from me - any news of another release?

**Comment by tshirtman** [comment]
On the way, sorry for the long delay… https://github.com/kivy/pyjnius/commit/ede72eb1c9a8eee31174141c038916ddd5e31fae/checks?check_suite_id=342723315

**Comment by tshirtman** [comment]
https://pypi.org/project/pyjnius/ done

**Comment by cmacdonald** [comment]
Thank you @tshirtman.
