### ISSUE TITLE
jnius.jnius.javaexception in kivy plyer vibrate

### ISSUE THREAD

**Issue by eugene2ko** [kivy/pyjnius#442]
**I wan't test plyer library with kivy and i tried to test a simple android vibrate. The app end with this log :**

```
`I python  :    File "jnius/jnius_export_class.pxi", line 1034, in jnius.jnius.JavaMultipleMethod.__call__

 I python  :  jnius.jnius.JavaException: No methods matching your arguments, available: [u'(ILjava/lang/String;[JILandroid/media/AudioAttributes;)V', u'(ILjava/lang/String;JLandroid/media/AudioAttributes;)V']

 I python  : Python for android ended.`
```

**Python Code:**
```
`from plyer import vibrator

 vibrator.vibrate(10)`
```

**I used different versions of pip packages - same result 
Last versions:**
_p4a == 2019.8.9
pyjnius == 1.2.0
jnius == 1.1.0
plyer == 1.4.2
cython == 0.28.2
kivy == 1.11.1_

_android-ndk-r17c-linux-x86_64
python3; openjdk-8-jdk_

`p4a apk  --permission VIBRATE --requirements==kivy,python3,plyer,pyjnius`

**Comment by aldwinaldwin** [comment]
I have the same issue. Python3.

**Comment by tomgold182** [comment]
same issue here

**Comment by goffi-contrib** [comment]
Issue was in Plyer and it is fixed in git (not released yet), this pyjnius issue can probably be closed.

**Comment by tshirtman** [comment]
ok, thanks.
