### ISSUE TITLE
Error on pip install pyjnius: Microsoft visual c++ 14.0 is required.

### ISSUE THREAD

**Issue by suhas-kadam** [kivy/pyjnius#447]
I have already installed latest microsoft visual c++ 2019; still facing the same issue.

>>pip install pyjnius
Collecting pyjnius
  Using cached https://files.pythonhosted.org/packages/b6/57/c90acf31322e6417f06
c90410dbfcb149633a6006b7efbf99dfebe177c1f/pyjnius-1.2.0.tar.gz
Requirement already satisfied: six>=1.7.0 in c:\programdata\anaconda3\lib\site-p
ackages (from pyjnius) (1.10.0)
Requirement already satisfied: cython in c:\programdata\anaconda3\lib\site-packa
ges (from pyjnius) (0.25.2)
Building wheels for collected packages: pyjnius
  Building wheel for pyjnius (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools,
 tokenize; sys.argv[0] = '"'"'C:\\Users\\Suhas\\AppData\\Local\\Temp\\pip-instal
l-6irth04d\\pyjnius\\setup.py'"'"'; __file__='"'"'C:\\Users\\Suhas\\AppData\\Loc
al\\Temp\\pip-install-6irth04d\\pyjnius\\setup.py'"'"';f=getattr(tokenize, '"'"'
open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f
.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users
\Suhas\AppData\Local\Temp\pip-wheel-l2micwlk' --python-tag cp36
       cwd: C:\Users\Suhas\AppData\Local\Temp\pip-install-6irth04d\pyjnius\
  Complete output (31 lines):
  C:\Progra~1\Java\jdk-11.0.4
  WARNING: Not able to assign machine() = AMD64 to a cpu value!
           Using cpu = 'i386' instead!
  JDK_HOME: C:\Progra~1\Java\jdk-11.0.4

  JRE_HOME: None

  warning: [options] bootstrap class path not set in conjunction with -source 6
  warning: [options] source value 6 is obsolete and will be removed in a future
release
  warning: [options] target value 1.6 is obsolete and will be removed in a futur
e release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-op
tions.
  4 warnings
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying jnius_config.py -> build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\jnius
  copying jnius\reflect.py -> build\lib.win-amd64-3.6\jnius
  copying jnius\signatures.py -> build\lib.win-amd64-3.6\jnius
  copying jnius\__init__.py -> build\lib.win-amd64-3.6\jnius
  creating build\lib.win-amd64-3.6\jnius\src
  creating build\lib.win-amd64-3.6\jnius\src\org
  creating build\lib.win-amd64-3.6\jnius\src\org\jnius
  copying jnius\src\org\jnius\NativeInvocationHandler.class -> build\lib.win-amd
64-3.6\jnius\src\org\jnius
  copying jnius\src\org\jnius\NativeInvocationHandler.java -> build\lib.win-amd6
4-3.6\jnius\src\org\jnius
  running build_ext
  cythoning jnius\jnius.pyx to jnius\jnius.c
  building 'jnius' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C+
+ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyjnius
  Running setup.py clean for pyjnius
Failed to build pyjnius
Installing collected packages: pyjnius
  Running setup.py install for pyjnius ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptool
s, tokenize; sys.argv[0] = '"'"'C:\\Users\\Suhas\\AppData\\Local\\Temp\\pip-inst
all-6irth04d\\pyjnius\\setup.py'"'"'; __file__='"'"'C:\\Users\\Suhas\\AppData\\L
ocal\\Temp\\pip-install-6irth04d\\pyjnius\\setup.py'"'"';f=getattr(tokenize, '"'
"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"')
;f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\U
sers\Suhas\AppData\Local\Temp\pip-record-bdmt65aa\install-record.txt' --single-v
ersion-externally-managed --compile
         cwd: C:\Users\Suhas\AppData\Local\Temp\pip-install-6irth04d\pyjnius\
    Complete output (31 lines):
    C:\Progra~1\Java\jdk-11.0.4
    WARNING: Not able to assign machine() = AMD64 to a cpu value!
             Using cpu = 'i386' instead!
    JDK_HOME: C:\Progra~1\Java\jdk-11.0.4

    JRE_HOME: None

    warning: [options] bootstrap class path not set in conjunction with -source
6
    warning: [options] source value 6 is obsolete and will be removed in a futur
e release
    warning: [options] target value 1.6 is obsolete and will be removed in a fut
ure release
    warning: [options] To suppress warnings about obsolete options, use -Xlint:-
options.
    4 warnings
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying jnius_config.py -> build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\jnius
    copying jnius\reflect.py -> build\lib.win-amd64-3.6\jnius
    copying jnius\signatures.py -> build\lib.win-amd64-3.6\jnius
    copying jnius\__init__.py -> build\lib.win-amd64-3.6\jnius
    creating build\lib.win-amd64-3.6\jnius\src
    creating build\lib.win-amd64-3.6\jnius\src\org
    creating build\lib.win-amd64-3.6\jnius\src\org\jnius
    copying jnius\src\org\jnius\NativeInvocationHandler.class -> build\lib.win-a
md64-3.6\jnius\src\org\jnius
    copying jnius\src\org\jnius\NativeInvocationHandler.java -> build\lib.win-am
d64-3.6\jnius\src\org\jnius
    running build_ext
    skipping 'jnius\jnius.c' Cython extension (up-to-date)
    building 'jnius' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\programdata\anaconda3\python.
exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Suha
s\\AppData\\Local\\Temp\\pip-install-6irth04d\\pyjnius\\setup.py'"'"'; __file__=
'"'"'C:\\Users\\Suhas\\AppData\\Local\\Temp\\pip-install-6irth04d\\pyjnius\\setu
p.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'ex
ec'"'"'))' install --record 'C:\Users\Suhas\AppData\Local\Temp\pip-record-bdmt65
aa\install-record.txt' --single-version-externally-managed --compile Check the l
ogs for full command output.

**Comment by tshirtman** [comment]
we now have wheels, they are not officially released yet, but you can try them from https://test.pypi.org/project/pyjnius/1.2.1.dev4/#files

**Comment by tshirtman** [comment]
wheels have been released on pypi, please open a new bug report if you have issues with them.
