### ISSUE TITLE
cast to interface, java.lang.Object methods not available

### ISSUE THREAD

**Issue by cmacdonald** [kivy/pyjnius#455]
jnius doesnt expose methods of java.lang.Object for references cast to interfaces.

For instance, the following Java code works:
```
import java.util.Map
import java.util.HashMap
var hmap = new HashMap<String,String>();
hmap.put("a", "1")
((Map<String,String>)hmap).toString()
```

The following Python does not:
```
from jnius import autoclass
from jnius import cast
mapClass = autoclass('java.util.HashMap')
hmap = mapClass()
hmap.put("a", "1")
print(thehmap.toString())
mmap = cast('java.util.Map', hmap)
mmap.toString()
```
gives
> AttributeError: 'java.util.Map' object has no attribute 'toString'

I would contend that any instantiated interface must extend Object, by virtue of the fact that it is instantiated.

Similar problems with .getClass()

**Comment by tshirtman** [comment]
i don't have a fix yet, but the specification is indeed clear on that https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.2 it is a bug on our side. Trying to add add Objects method implicitly in autoclassed interfaces…

**Comment by cmacdonald** [comment]
Thanks @tshirtman, this is appreciated. I have made a small comment on the PR.

**Comment by cmacdonald** [comment]
@tshirtman - i think this has a regression - see #465
