### ISSUE TITLE
pyjnius is not thread-safe

### ISSUE THREAD

**Issue by misja** [kivy/pyjnius#46]
The following results in a core dump:

``` python
import threading
from jnius import autoclass

class MyThread(threading.Thread):
    def run(self):
        autoclass('java.lang.System').out.println('Hello world')

for i in range(2):
    MyThread().start()
```

**Comment by NewAge12** [comment]
Anyone had any luck getting threading to work on android??

**Comment by jsnieg** [comment]
> Anyone had any luck getting threading to work on android??

I'm aware the reply is from 2 years ago but, `Pyjnius` does not seem to be thread safe in some cases. When trying to Thread a function which is responsible for picking up Bluetooth signals through `BroadcastReceiver` it throws out exceptions that it cannot find `GenericBroadcastReceiver`. I'm aware that probably it loses that class when its Threaded separate from Kivy but still. Very frustrating. And handling lots of signals is necessary for a project I'm working on.
