### ISSUE TITLE
Shared interprocess memory between Python and Java

### ISSUE THREAD

**Issue by ctrueden** [kivy/pyjnius#468]
With Python 3.8, multiprocessing now has support for [shared_memory](https://docs.python.org/3/library/multiprocessing.shared_memory.html) between processes. (See [here](https://bugs.python.org/issue35813) for initial merged patch.)

My group is planning to pursue a Java-Python integration using it, to avoid copying large image data structures between Python and Java. However, for this to work as awesomely as PyJNIus does, we also need to use messaging to wrap Python objects to Java and vice versa. The [py4j](https://www.py4j.org/) project works in this direction. This may be interesting for PyJNIus as well because: 1) you would no longer have to load the JVM from the Python process; 2) you could have multiple JVMs going at once; 3) you would not have to start upon import of jnius; 4) it might also solve #457's point (3) about making the API usage more transparent—i.e. not explicitly converting between python-side and java-side data structures.

Feel free to close as out of scope. We just wanted to make sure you knew about the `multiprocessing.shared_memory` feature.

**Comment by tshirtman** [comment]
Thanks for the information, i don't think i will work on this (plenty to do already :grimacing:), but if someone wants to, that's welcome.
