### ISSUE TITLE
Cannot access PythonActivity from autoclass

### ISSUE THREAD

**Issue by B3NNJ4** [kivy/pyjnius#477]
Everytime I write this line of code
`PythonActivity = autoclass('org.kivy.android.PythonActivity')` or maybe this one `PythonActivity = autoclass('org.renpy.android.PythonActivity')` I get the same error, which is `jnius.JavaException: Class not found b'org/kivy/android/PythonActivity'` for the former and `jnius.JavaException: Class not found b'org/renpy/android/PythonActivity'` for the latter. I'm using Python 3.7 64-bit with pyjnius(1.2.1).

**Comment by tshirtman** [comment]
This code will only work when the app runs on android, in a kivy app, is that how you are running it?

**Comment by B3NNJ4** [comment]
Not really. I've never actually tried that. Let me see if it works
