### ISSUE TITLE
strip error on env path

### ISSUE THREAD

**Issue by chenzhiw** [kivy/pyjnius#481]
[pyjnius/jnius/env.py](https://github.com/kivy/pyjnius/blob/master/jnius/env.py) line 234
`jre_home = dirname(get_jre_home(platform)).strip('jre')`
The [str.strip()](https://docs.python.org/3/library/stdtypes.html#str.strip) method will strip the letters 'j', 'r', and 'e'. If  JAVA_HOME is /path/to/java8-oracle, `dirname(get_jre_home(platform)).strip()` will return /path/to/java8-oracl. The last letter 'e' is removed!

**Comment by glyg** [comment]
I can confirm this issue. Opened a PR with a quick fix

**Comment by tshirtman** [comment]
Ugh, thanks for the report and fix!

**Comment by glyg** [comment]
thank you for kivy!
