### ISSUE TITLE
JVM exception occurred: D0071S: Value not among the ENUMERATED: index = 15'

### ISSUE THREAD

**Issue by sabari4857** [kivy/pyjnius#482]
Hi 
Need urgent help,
I was using the Jnius library for long time...suddenly i got the below error.please help.

=================================================== BEGIN REPORT
An exception was raised: JavaException('JVM exception occurred: D0071S: Value not among the ENUMERATED: index = 15',)
Exception occurred in file "jnius/jnius_utils.pxi" on line 91
---------------------------------------------------

--------------------------------------------------- Exception Details

JavaException('JVM exception occurred: D0071S: Value not among the ENUMERATED: index = 15',)

  File "jnius/jnius_export_class.pxi", line 1047, in jnius.JavaMultipleMethod.__call__

  File "jnius/jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__

  File "jnius/jnius_export_class.pxi", line 846, in jnius.JavaMethod.call_method

  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception

**Comment by tshirtman** [comment]
This is not a hotline, if you want help, give as much info as possible, if possible a way to reproduce. Don't except immediate help anyway, there is no support level agreement, and i'm on vacations anyway.

**Comment by sabari4857** [comment]
let me replicate the issue and give you information.Thanks for the reply.

**Comment by Julian-O** [comment]
No response after 3 years. Closing as can't repro.
