### ISSUE TITLE
Inheriting methods from Java in PythonJavaClass

### ISSUE THREAD

**Issue by cmacdonald** [kivy/pyjnius#485]
How do I inherit fields and methods from a Java parent class into a PythonJavaClass?

Consider the following Java base class:
```
package org.jnius;
public abstract class AbstractParent {
    int value=0;
    protected AbstractParent(){}
    public void doOne() { value = 1; }
    public abstract void doTwo();
}
```

```python
class TestAbstract(with_metaclass(MetaJavaClass, PythonJavaClass)):
            __javaclass__ = 'org/jnius/AbstractParent'
            __javainterfaces__ = []
            
            @java_method('()Z')
            def doTwo(self):
                print("hello")
```

I can call doTwo(), but I cannot access doOne() from Python, nor value, i.e. neither of the following two statements work:
```
value = JavaField('()I;', static=False)
doOne = JavaMethod('()Z')
```
Moreover, we can't mix Python classes that are children of PythonJavaClass and JavaClass.

It seems that PythonJavaClass (c.f. resolve_fields() in jnius_export_class.pxi) only examines `self.__class__.__dict__` to find methods to add to the proxy class, while I could contend that, similar to `autoclass()`, it should walk the interfaces and superclasses.

**Comment by tshirtman** [comment]
I'm not sure i follow but
- we don't actually have a way to subclass/inherit from python at all, maybe it's possible in the JVM, but it doesn't seem to be in the android version of java, which is where we'd want it the most, i did spent quite some time looking into this without success, that was years ago, but i don't think things changed, i'd love to be proven wrong though.
- i don't think you should be able to instanciate an abstract class, i'm not sure what happens there, but it's probably conceptually wrong.

**Comment by cmacdonald** [comment]
> we don't actually have a way to subclass/inherit from python
Yes, I missed this. I think all needed is a documentation clarification.

**Comment by tshirtman** [comment]
i think that was solved by your doc update PR, closing, let me know if you feel more is needed.

**Comment by xloem** [comment]
Hey, could sombody link to the documentation PR here, so googlers trying to do this can find more information?

I talked with tshirtman briefly in discord, and he linked me to https://github.com/tshirtman/longface/blob/master/parse.py which apparently was the last effort to solve this.  He's not aware of a way to do this with Android's JNI.

It looks to me like it might be possible by making java classes for all the abstract classes that export the abstract methods as native, and then make python classes to inherit from that by default call the superclass implementations of the abstract methods.  Might send it straight into the python-for-android repository's in-tree 'android' recipe if anybody ever succeeded at that.
