### ISSUE TITLE
Python 3.8 cannot start JVM, when jnius_config is set.

### ISSUE THREAD

**Issue by Csega** [kivy/pyjnius#486]
Hi guys,

I have the following problem. I installed pyjnius (version 1.2.1) using Anaconda (with Python 3.8.1). Anaconda is really comfortable, it installs a JDK as well. As far as I'm concerned, everything needed is installed, and the environment variables are set (both JAVA_HOME is correct and jvm.dll is added to the path). And the good news is, that the 

```python
import jnius
from jnius import autoclass
```

snippet work flawlessly. The problem starts, when I want to set some JVM options. This code snippet does not work:

```python
import jnius_config
jnius_config.add_options('-Xrs', '-Xmx512m')
import jnius
```

I get the following error message:

```
C:\Users\[my_username]\tools\Continuum\anaconda3\envs\EDVIS\Library
Unrecognized option:
JVM failed to start
C:\Users\[my_username]\tools\Continuum\anaconda3\envs\EDVIS\Library\jre\bin\client
C:\Users\[my_username]\tools\Continuum\anaconda3\envs\EDVIS\Library\jre\bin\server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[my_username]\tools\Continuum\anaconda3\envs\EDVIS\lib\site-packages\jnius\__init__.py", line 48, in <module>
    raise Exception("Unable to create jni env, no jvm dll found.")
Exception: Unable to create jni env, no jvm dll found.
```

I was able to find this part of code in the source, which is in the ./jnius/jnius_jvm_desktop.pxi from line 50-70. The problem is, that I can't see, what is the problem! The args variable is set, filled up with the options global variable coming from jnius_config. But I can't see, that the non-empty args variable how can cause the JVM to fail. Especially with valid switches...

Can you help me solve this?

My system is:
Windows 10 64-bit
Anaconda 3 2019.10
Python 3.8.1
Pyjnius 1.2.1
OpenJDK 11.0.1

Cheers,
Csega

**Comment by Csega** [comment]
Any comment on this? Nobody run in this problem so far? Not even @tshirtman ?

**Comment by cmacdonald** [comment]
Does the same environment work on a different Python environment. The code that searches for the JDK is a bit convoluted, I had to just add print() statements to figure out where it was looking.

**Comment by Csega** [comment]
Hi @cmacdonald! Thanks for the answer! :) I tried the same (in the same environment) with Python 3.7.6 and it works! So it seems, that this is really an issue with Python 3.8...

**Comment by cmacdonald** [comment]
Hmmm, I had meant to write different _Java_ version. There can be differences in the JDK layout between versions. For Linux, setting the JAVA_HOME env var really helps.

**Comment by Csega** [comment]
Oh, I see. I tried it in a pure Python 3.8 environment with Java 8 on Windows 10, and the same problem occured. So I think it is something to do with Python 3.8 compatibility, but I can't put my finger on it.

**Comment by tshirtman** [comment]
Hey, sorry for lack of answer, i've had to do some tricks for the windows build to work with python3.8, as they changed how the dll lookup work, i'm not sure that's 100% correct, but it worked for my tests.

i think that was it https://github.com/kivy/pyjnius/blob/master/.github/workflows/create.yml#L55 but it's been a few months.

**Comment by Csega** [comment]
Sorry for the late answer, I did not notice your comment so far. :(

However, now I tried the whole procedure I wrote at my first comment on this issue, and it still don't work with pyjnius 1.3.0. I looked at your file, but I don't know, how to test it for myself. Can you give me directions to it?

**Comment by cmacdonald** [comment]
I had issues with OpenJDK on Linux, and ended up rewriting a lot of the boot code.
Are you able to try installing and compiling this branch:
https://github.com/cmacdonald/pyjnius/blob/java_home
You would need MS Visual Studio tools installed though.

**Comment by hx2A** [comment]
How well does this work if you try a JDK that is not installed via Anaconda?

**Comment by chbauman** [comment]
I am experiencing the same issue, the JVM is not starting when I try to set options.

- OS: Windows 10 64-bit
- Python: 3.8.10
- pyjnius: 1.3.0
- java: openjdk version "14.0.1" 2020-04-14

Example:
```
jnius_config.add_options("-Xmx4096")
```
Output:
```
Unrecognized option: 
Unrecognized option: 
...
Exception: Unable to create jni env, no jvm dll found.
```
 I am *not* using Anaconda.

**Comment by chbauman** [comment]
As a workaround I am setting the environment variable `_JAVA_OPTIONS`  before running my python script. This seems to work. E.g.: (Powershell on Windows 10)
```
$env:_JAVA_OPTIONS = "-Xmx2000m"
python .\python_script_using_pyjnius.py
```
