### ISSUE TITLE
How does Pyjnius use instance methods as static methods?

### ISSUE THREAD

**Issue by pakal** [kivy/pyjnius#488]
Python-for-android and other packages use these types of statements, but I can't understand how they can work, since they loads CLASSES (ehere PythonActivity), and call normal, non-static METHODS on them.

How can it be possible? These methods use "this" in their implementation, is there a magic lookup of mActivity or mService static instances on these classes to do the work? If so I'd gladly document it.

```
        python_activity = autoclass('org.kivy.android.PythonActivity')
        python_activity.checkCurrentPermission(permission + "")
```

**Comment by tshirtman** [comment]
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/android/src/android/activity.py#L4
this one uses mActivity, do you have an exmaple of where we do this call on the class?

**Comment by pakal** [comment]
Yes there are multiple similar calls in python-for-android, eg. https://github.com/kivy/python-for-android/blob/8740267d82fc3797a56ee355c9e69f4f30b35a84/pythonforandroid/recipes/android/src/android/permissions.py#L577

I tested it in my own app, the method call works whereas there is no instance explicitly involved.
