### ISSUE TITLE
Strings Encoding Issues in Python 3 due to latest Cython updates

### ISSUE THREAD

**Issue by chavarinbonbyn** [kivy/pyjnius#491]
This is related to the closed issue #300  

The latest release version of Cython (0.29.15) is causing pyjnius issues related to string encoding. I have experienced this issue in Python v3.6.9 for Ubuntu 16.04.

****** Python code
try:
    from jnius import autoclass
except KeyError:
    import os
    os.environ['JDK_HOME'] = "/usr/lib/jvm/java-8-openjdk-amd64"
    os.environ['JAVA_HOME'] = "/usr/lib/jvm/java-8-openjdk-amd64"
    from jnius import autoclass

Stack = autoclass('java.util.Stack')
stack = Stack()
stack.push('hello')
stack.push('world')

print(stack.pop())
print(stack.pop())

**** Output:
åÓÍ
ål

**Comment by cmacdonald** [comment]
Trying to think ahead for the maintainers, is it possible to have a testcase PR that shows this? Then the regression would show up in the Github workflows?

**Comment by hx2A** [comment]
Does PR #524 fix this? I fixed some encoding issues for Python 3.

```
In [1]: from jnius import autoclass                       

In [2]: Stack = autoclass('java.util.Stack') 
   ...: stack = Stack() 
   ...: stack.push('hello') 
   ...: stack.push('world')                               
Out[2]: 'world'

In [3]: print(stack.pop())                                
world

In [4]: print(stack.pop())                                
hello

In [5]: import cython; cython.__version__                 
Out[5]: '0.29.15'
```

And the PR has unit tests.

**Comment by tshirtman** [comment]
yes, i was wondering the same, my test in #496 seems to pass, but the test somehow breaks another test, not sure why now, but the test passes on its own, so that seems good enough for me to close.
