### ISSUE TITLE
Add __exit__ for java.io.Closable or java.io.Autoclosable methods

### ISSUE THREAD

**Issue by cmacdonald** [kivy/pyjnius#494]
Patch for autoclass. For bonus points, it would be good to have an API where we could automatically decorate newly created object with appropriate dunder methods.

**Comment by cmacdonald** [comment]
#497 merged. Thank you @tshirtman. Closing.

**Comment by tshirtman** [comment]
no thank *you* :), the way you implemented it is great, as it'll allow making using java objects in a lot of more pythonic ways (support for iter(), `in`, and probably others) <3
