### ISSUE TITLE
CI: trigger the build of documentation or readthedoc on release.

### ISSUE THREAD

**Issue by tshirtman** [kivy/pyjnius#531]
we shouldn't need to think of connecting to readthedocs and click a button to have up to date docs, it should be possible to automate that.

**Comment by misl6** [comment]
Closing as the webhook (which has been updated last week) worked great on the latest push.
Now https://pyjnius.readthedocs.io/en/latest/ is in sync.

**Comment by cmacdonald** [comment]
The RTD still has:
```html
<title>Welcome to Pyjnius &mdash; Pyjnius 1.0a1 documentation</title>
```

Can we find a way to get the version number automatically into RTD?
