### ISSUE TITLE
update installation documentation

### ISSUE THREAD

**Issue by tshirtman** [kivy/pyjnius#532]
the documentation stills detail the compilation steps for installation on desktop, which shouldn't be always necessary now, since wheels are provided.
https://pyjnius.readthedocs.io/en/latest/installation.html

while it's good that it details them for those who want to install from source, most people would benefit from a simpler installation process, like the one in README.md.

**Comment by misl6** [comment]
Closing as the webhook (which has been updated last week) worked great on the latest push.
Now https://pyjnius.readthedocs.io/en/latest/ is in sync.

**Comment by cmacdonald** [comment]
This can be closed now

**Comment by misl6** [comment]
Closed via #700
