### ISSUE TITLE
I can't import caste

### ISSUE THREAD

**Issue by Jacques-Joao** [kivy/pyjnius#543]
I'm new to programming and this is my first time using jnius.

I intend to create an android application that makes calls to different numbers, so I decided to use jnius and use the autoclass and cast functions, making an optimized import, I managed to import the autoclass but not cast.

My code is supposed to look like this:

 ```python
from jnius import autoclass
from jnius import cast

Intent = autoclass('android.content.Intent')
Uri = autoclass('android.net.Uri')
PythonActivity = autoclass('org.renpy.android.PythonActivity')
intent = Intent(Intent.ACTION_CALL)
intent.setData(Uri.parse("tel:" + num))
currentActivity = cast('android.app.Activity', PythonActivity.mActivity)
currentActivity.startActivity(intent)
```

- I'm programming using windows 10, Python 3.7.4, and my IDE is Pycharm, and I'm using jnius 1.3.0 (the last one at the moment)
(This information may be useful)

**Comment by tshirtman** [comment]
1/ you should be able to import both at the same time. `from jnius import autoclass, cast`
2/ running this code on windows won't work anyway, as you don't have access to the android api there, make sure to test on android.
