### ISSUE TITLE
Java object doesn't have hash code when checking in Python with the new pyjnius

### ISSUE THREAD

**Issue by LilyNL** [kivy/pyjnius#547]
Hi,

My code below **works well** with pyjnius-1.2.0-py3.6.egg-info
but got error with pyjnius-1.3.0
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: unhashable type: 'UUID'

Could you give more information on this? Is it no more supported in pyjnius or is it a bug and will be fixed in the new version?

Thank you in advance for your response.
Lily.

```
from jnius import autoclass
UUID = autoclass('java.util.UUID')
k = UUID.fromString('ac0002d8-44f8-42af-af04-a340ed9bf016')
k.__hash__()

```

**Comment by cmacdonald** [comment]
You can fix trivially using by monkeypatching the `__hash__()` method to `hashCode()`, as follows:
```
UUID.__hash__ = UUID.hashCode
k = UUID.fromString('ac0002d8-44f8-42af-af04-a340ed9bf016')
```

A more natural way for you to fix this would be to add to the Jnius `protocol_map`:
```
from jnius import autoclass, protocol_map
protocol_map['java.util.UUID'] = {'__hash__' : lambda self: self.hashCode() }
UUID = autoclass('java.util.UUID')
k = UUID.fromString('ac0002d8-44f8-42af-af04-a340ed9bf016')
k.__hash__()
```

I don't think we want to associate `hashCode()` to `__hash__()` by default, as not all implementations of hashCode are proper.

However, I'm not sure if this is a true regression or not compared to v1.2.0. There was no mention of `__hash__` in reflect.py around that version

**Comment by LilyNL** [comment]
Thank you for your help.

Actually I use the UUID variable as key for a dictionary, d[k] = v

UUID.__hash__ = UUID.hashCode works for me, protocol_map not.

**Comment by cmacdonald** [comment]
> protocol_map not.

Strange, works ok for me.

**Comment by LilyNL** [comment]
Hi,
Sorry that I was not clear in my previous email.

Code with protocol_map works with the given example above. However, when I run the code below:

```
from jnius import protocol_map
protocol_map['java.util.UUID'] = {'__hash__': lambda self: self.hashCode()}

dictionary = dict()
keySet = jMap.keySet().toArray()
for key in keySet:
	dictionary[key] = jMap.get(key)
return dictionary

```

I got error 

>  error: unhashable type: 'java.util.UUID'
> Traceback (most recent call last):
>   File "jnius\jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
>   File "jnius\jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
>   File ...
>   ...
>   File "myCode.py", line xx, in myFunction
>     dictionary[key] = jMap.get(key)
> TypeError: unhashable type: 'java.util.UUID'
> 

The following code works.
```
        from jnius import autoclass
        UUID = autoclass('java.util.UUID')
        UUID.__hash__ = UUID.hashCode

        dictionary = dict()
        keySet = jMap.keySet().toArray()
        for key in keySet:
            dictionary[key] = jMap.get(key)
        return dictionary

```

**Comment by cmacdonald** [comment]
This works for me:
```python
from jnius import protocol_map, autoclass
protocol_map['java.util.UUID'] = {'__hash__': lambda self: self.hashCode()}
UUID = autoclass('java.util.UUID')
k = UUID.fromString('ac0002d8-44f8-42af-af04-a340ed9bf016')
jMap = autoclass("java.util.HashMap")()
jMap.put(k, 2)
dictionary = dict()
keySet = jMap.keySet().toArray()
for key in keySet:
	dictionary[key] = jMap.get(key)
  
print( '__hash__' in dir(jMap.keySet().toArray()[0]) )
```

Are you creating jMap in Java instead?

**Comment by LilyNL** [comment]
Yes, I got the jMap when running methods in a .jar.
I was converting a received jMap in Java to a dictionary in Python.
