### ISSUE TITLE
Documentation should be elaborated significantly, working examples should be supplied for Android

### ISSUE THREAD

**Issue by lokapal** [kivy/pyjnius#552]
I'm trying to detect screen resolution in Kivy for Android:

from kivy.utils import platform

if platform == 'android':
    from jnius import autoclass
    DisplayMetrics = autoclass('android.util.DisplayMetrics')
    metrics = DisplayMetrics()
    Height_of_screen = metrics.heightPixels
    Width_of_screen = metrics.widthPixels

print("Height = "+ str(Height_of_screen))
print("Width = " + str(Width_of_screen))

Both height and width = 0 in logcat.txt.

Some examples are concerning class 'android.util.DisplayMetrics', some are concerning class 'org.renpy.android.Hardware'  and NO docs/examples about both classes and how to use properties from, e.g. DisplayMetrics.

And the reason of all this hell is damn simple - Kivy doesn't want to transfer display parameters from graphics library to user...

**Comment by Julian-O** [comment]
(Just a general life tip: avoid ascribing negative motivations to people on the Internet without strong evidence - especially when you want help from developers giving you free tools.)
