### ISSUE TITLE
Access Denied. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by Ndohjapan** [kivy/pyjnius#554]
Please, I have tried installing pyjnius for my project but each time I do so using the pip install command, I get the error bellow.
`ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python36-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Temp\\pip-install-4qsfikmm\\pyjnius\\setup.py'"'"'; __file__='"'"'C:\\Temp\\pip-install-4qsfikmm\\pyjnius\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Temp\pip-pip-egg-info-k0oh_gxs'
         cwd: C:\Temp\pip-install-4qsfikmm\pyjnius\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-install-4qsfikmm\pyjnius\setup.py", line 95, in <module>
        compile_native_invocation_handler(*get_possible_homes(PLATFORM))
      File "C:\Temp\pip-install-4qsfikmm\pyjnius\setup.py", line 87, in compile_native_invocation_handler
        join('jnius', 'src', 'org', 'jnius', 'NativeInvocationHandler.java')
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subprocess.py", line 306, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subprocess.py", line 287, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subprocess.py", line 1017, in _execute_child
        startupinfo)
    PermissionError: [WinError 5] Access is denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by Ndohjapan** [comment]
Hope for help.

**Comment by hx2A** [comment]
You are doing this on Windows, and it looks like you don't have write access to one of the directories the install process is using. This might be an issue with the Windows user you are using when you log in. One approach is to try giving your command prompt administrator rights. You can do that by starting a new command prompt window with admin rights through the Windows start menu.

My personal experience with Python on Windows is limited to using Anaconda to manage everything. Anaconda works well and seems to make up for the shortcomings of Windows and other cross-platform idiosyncracies.
