### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by obfusk** [kivy/pyjnius#559]
Looks like [`setup-java` used to always install an x64 version even if x86 was specified](https://github.com/actions/setup-java/pull/95).

* There don't seem to be x86 ubuntu images available.
* Installing i386 support on amd64 ubuntu should not be hard.
* Not sure if x86 java works w/ x64 Python though.

**Comment by cmacdonald** [comment]
I see that Android is "dropping support for 32bit". Is 32 bit Android still a target for Kivy?

**Comment by tshirtman** [comment]
> Looks like setup-java used to always install an x64 version even if x86 was specified.
    There don't seem to be x86 ubuntu images available.
    Installing i386 support on amd64 ubuntu should not be hard.
    Not sure if x86 java works w/ x64 Python though.

Ah, that would explain why https://github.com/kivy/pyjnius/pull/536 failed to build on x86 i guess, 

> I see that Android is "dropping support for 32bit". Is 32 bit Android still a target for Kivy?

What's the source of that? I see android studio dropping support for 32bit developer machines, not for 32bit targets, and aside that that android stopped supporting 32bit only applications, this is already in place, and forces developpers to first upload a 64bit version, and then, if they want, add a 32bit version to support the corresponding devices. Is there anything new?

**Comment by cmacdonald** [comment]
> What's the source of that? ... Is there anything new?

Umm only the google search infocard for Android. So nothing reputable, and nothing I spent more than one second looking at. Looking more carefully, the source is the Android Wikipedia page which says that 32bit ARM is being dropped.

Just trying to think how to test 32bit python situations on GitHub then. In jnius, the JVM library arch-sensitive location is computed based on platform.machine() - see env.py

**Comment by tshirtman** [comment]
Yep, arm is going to drop it next year or so, but 32 bit phones are still going to be around for a few years, it's certainly quite early for us to think about dropping it.

seems the CI in #536 passed after i rebased master and force pushed earlier. So maybe the fix from the setup-java action solved it.
We are still ignoring 32bit for ubuntu and osx, but we have it for windows.

**Comment by obfusk** [comment]
AFAIK running the 32-bit linux tests using the official 32-bit python docker images should work (with just a few lines of code).

A p4a arm build that also runs the test suite would be nice (but that seems like more work).
