### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by pkor** [kivy/pyjnius#57]
I have no idea where to begin installing this. I want to use it with kivy on android for the tts module. I can't find any documentation except for how to use it after it's installed. I tried using 'make' but my system doesn't recognize the 'make' command even after installing make. Need more detail on this. Maybe step by step (including installing make).

**Comment by harishankarv** [comment]
After wasting hours on how to set this up properly, this is what worked for me. I have tried to be as verbose as possible. <br>
1. Download and install jdk (if not installed)
    http://www.oracle.com/technetwork/java/javase/downloads/index.html
 
2. System/Environment Variables (replace  jdk1.7.0_79  with your jdk version )
    - Add to Environment Variables:
        * JDK_HOME C:\Program Files\Java\jdk1.7.0_79\
        * PATH C:\Program Files\Java\jdk1.7.0_79\jre\bin\server\
    - Add to System Variables:
        * PATH: C:\Program Files\Java\jdk1.7.0_79\bin\
 
3.	Install pip (if not installed)
    - https://pip.pypa.io/en/latest/installing/
 
4.	Install Cython (if not installed):
    - Install wheel: `pip install wheel`
    - Install cython:
        * Download cython for windows: http://www.lfd.uci.edu/~gohlke/pythonlibs/#cython
        * `pip install Cython-0.24-cp35-cp35m-win_amd64.whl` (use appropriate filename)
 
5.	Install  Microsoft Visual C++ Compiler for Python 2.7:
    - http://aka.ms/vcpython27 <br>
    Python modules can be part written in C (typically for speed).  If you try to install such a package with Pip (or setup.py), it has to compile that C/C++ from source.  Refer:
http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat/26127562#26127562
    - Install setuptools for the compiler to work: <br>
https://pypi.python.org/pypi/setuptools#windows-simplified
 
6.	Download pyjnius source and install:
    - https://github.com/kivy/pyjnius
    - `python setup.py install`

**Comment by dessant** [comment]
@harishankarv, nice work :+1: . This could actually land in the pyjnius installation docs if you want to make a pr for it.

**Comment by harishankarv** [comment]
I just realized I may have posted in the wrong issue section. Maybe should have posted this [here](https://github.com/kivy/pyjnius/issues/147)?
Anywho, sure thing @dessant, I'll send a pull request!

**Comment by snoop911** [comment]
I just installed newer version of kivy 1.9.1, buildozer .32,  and Cython 0.21, yet I also get the jnius error:
 
  File "bluetooth_kivy.py", line 15, in <module>
    from jnius import autoclass
ImportError: No module named jnius

(I'm using the example from https://gist.github.com/tito/7432757 )

**Comment by LuisCarlosPallaresAscanio** [comment]
> 
> 
> Download windows package for mysysgit http://code.google.com/p/msysgit/,
> install it.
> Run the app.
> It should open a terminal
> cd to the directory kivy.bat is located in.
> type "git clone [http://github.com/kivy/pyjnius](https://github.com/kivy/pyjnius)"
> This should download pyjnius.
> now edit kivy.bat and add the path to pyjnius to PYTHONPATH
> close the terminal.
> 
> Now you should be able to import pyjnius in your.py file.
> 
> Best Regards
> 
> On Thu, Apr 11, 2013 at 1:41 AM, pkor [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Thanks! I wasn't aware that it came with python for android. If I want to
> > do testing before running on the android device I'll need to run it under
> > windows? To do that are there some more detailed instructions than the
> > above link?
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/[/issues/57](https://github.com/kivy/pyjnius/issues/57)#issuecomment-16198823
> > .

what do you mean by editing kivy.bat?

**Comment by LuisCarlosPallaresAscanio** [comment]
solución:
download the .whl:   https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyjnius
where you downloaded pip install [file].whl
