### ISSUE TITLE
How to get class name

### ISSUE THREAD

**Issue by enjoybeta** [kivy/pyjnius#570]
Inside Java, `Node.class.getName( )` can return a string (e.g.: `com.foo.bar`) representing the class name . How can we do similar thing in Python with pyjnius?

In another word, can we inherit a Java class in Python with pyjnius and obtain the class name of the Python class?

**Comment by cmacdonald** [comment]
Assuming Node is obtained from `autoclass()`, 
`Node._class.getName()` is what you seek.

Documentation patches greatly appreciated!

Your other question concerns *inheriting* a Java class in Python - thats not possible, for now. You can however create a Python class that implements an interface.

**Comment by enjoybeta** [comment]
Thanks, Node._class.getName() worked with autoclass().
