### ISSUE TITLE
Pyjnius in Python 3.9

### ISSUE THREAD

**Issue by juanjavatus** [kivy/pyjnius#573]
Hi,
I have installed Pyjnius with Python 3.7.5 an had no problem, but installation is not working with Python 3.9. Is there a way to do it?
Thanks in advance

**Comment by hx2A** [comment]
Can you elaborate on the installation problem? Are there any error messages?

**Comment by juanjavatus** [comment]
Puff--a lot! Here they are:

juanjo@juanjo-A52JK:~$ pip install pyjnius
Collecting pyjnius
  Using cached pyjnius-1.3.0.0.tar.gz (46 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/juanjo/.pyenv/versions/3.9.0rc1/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y2ond0_i/pyjnius/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y2ond0_i/pyjnius/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-f7tk_t0l
         cwd: /tmp/pip-install-y2ond0_i/pyjnius/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y2ond0_i/pyjnius/setup.py", line 95, in <module>
        compile_native_invocation_handler(*get_possible_homes(PLATFORM))
      File "jnius/env.py", line 172, in get_possible_homes
        get_jdk_home(platform),
      File "jnius/env.py", line 136, in get_jdk_home
        check_output(
      File "/home/juanjo/.pyenv/versions/3.9.0rc1/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/juanjo/.pyenv/versions/3.9.0rc1/lib/python3.9/subprocess.py", line 524, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hx2A** [comment]
Do you have Java installed? What happens when you type `which java` and `which javac` on the command line?

**Comment by juanjavatus** [comment]
Yes, I installed it. But when I type which java nothing happens...

**Comment by juanjavatus** [comment]
I tried in other way and this is the result:

juanjo@juanjo-A52JK:~$ java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

**Comment by juanjavatus** [comment]
Ups, solved, I don't know what I did wrong. Thank you for all the help.

juanjo@juanjo-A52JK:~$ pip install pyjnius
Collecting pyjnius
  Using cached pyjnius-1.3.0.0.tar.gz (46 kB)
Requirement already satisfied: six>=1.7.0 in ./.pyenv/versions/3.9.0rc1/envs/mainsystem/lib/python3.9/site-packages (from pyjnius) (1.15.0)
Requirement already satisfied: cython in ./.pyenv/versions/3.9.0rc1/envs/mainsystem/lib/python3.9/site-packages (from pyjnius) (0.29.21)
Using legacy 'setup.py install' for pyjnius, since package 'wheel' is not installed.
Installing collected packages: pyjnius
    Running setup.py install for pyjnius ... done
Successfully installed pyjnius-1.3.0

juanjo@juanjo-A52JK:~$ which java
/usr/bin/java

**Comment by tueda** [comment]
Is there any plan to upload Python 3.9 wheel on PyPI? Or will it be when the next release comes out?
