### ISSUE TITLE
How can I add pyjnius into my project?

### ISSUE THREAD

**Issue by everydaysayhello** [kivy/pyjnius#577]
How can I add pyjnius into my project instead of creating a new python-for-android project?Or how can I compile pyjnius into an Android '.so' file that I can call it with using 'import' in android platform？I need your help!Thank you very much!!!

**Comment by AndiEcker** [comment]
pyjnius will be automatically added to any kivy project that will be built
for android. buildozer <https://buildozer.readthedocs.io/en/latest/> is
helping you to build an APK for the android OS.

Please note that the import name of the pyjnius module is jnius, like e.g.
in

from jnius import autoclass


Am Do., 17. Dez. 2020 um 09:39 Uhr schrieb everydaysayhello <
notifications@github.com>:

**Comment by everydaysayhello** [comment]
Oh, well, I know how to use 'pyjnius', but I want to insert' pyjnius' into the Android project where I have written a lot of code, rather than create an empty Android 'pyjnius' project.

I can also compile 'pyjnius' into an Android '.so ' file to call directly, but I don't know how to compile it.

Thank you for your help very much！

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by AndiEcker** [comment]
Sorry but I don't understand what you mean.

Could you point me to your repository to check your (lot of) code?

Am Fr., 18. Dez. 2020 um 00:55 Uhr schrieb everydaysayhello <
notifications@github.com>:

**Comment by everydaysayhello** [comment]
To put it another way, how can I add 'pyjnius' to the Android project of the flutter project?
Thank you!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tshirtman** [comment]
pyjnius is a python library, do you have python integrated in your flutter project?

**Comment by everydaysayhello** [comment]
> pyjnius is a python library, do you have python integrated in your flutter project?

pyjnius is not a pure python library,So I have to compile it into so library to call it in Android environment, which requires cross compilation of pyjnius library.You can download python environment in the network.

**Comment by tshirtman** [comment]
I know, i'm one of the devs, but the question is about needing python to be able to make use of pyjnius.

**Comment by everydaysayhello** [comment]
> I know, i'm one of the devs, but the question is about needing python to be able to make use of pyjnius.

oh，sorry！Isn't it easy to package the python environment into Android? However, if I want to call Java through python, I must use your 'pyjnius' library. But I can't package the 'pyjnius' library and put it in my Python environment. Can you help me?
Thank you very much!

**Comment by tshirtman** [comment]
If you use https://github.com/kivy/python-for-android/ you'll have an apk with python inside it, and pyjnius will be there as well, if you already build an apk in another way and want to add python to it, i'm sure it's possible and other people did it, but i'm not knowledgeable enough to explain how.

Anyway, this is really more a support request than a bug report so i'll close, but you can come ask question on the chat or in another support channel if you want to discuss more.
