### ISSUE TITLE
Error in following installation on Ubuntu

### ISSUE THREAD

**Issue by yhryyq** [kivy/pyjnius#579]
I follow the Installation [https://pyjnius.readthedocs.io/en/stable/installation.html#installation](url), execute`sudo python setup.py install` and `make`. Then I execute `make tests`. But I got 32 errors.

**Error output:**

(cd tests; env CLASSPATH=../build/test-classes:../build/classes PYTHONPATH=..: pytest -v)
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.18rc1, pytest-4.6.11, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /mnt/c/Users/yhryy/Desktop/TryRealProj/projects/pyjnius-master/work
collected 13 items / 32 errors

======================================================== ERRORS ========================================================
_______________________________________ ERROR collecting tests/test_arraylist.py _______________________________________
test_arraylist.py:3: in <module>
    from jnius import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_assignable.py _______________________________________
test_assignable.py:5: in <module>
    from jnius import autoclass, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
____________________________________ ERROR collecting tests/test_bad_declaration.py ____________________________________
test_bad_declaration.py:5: in <module>
    from jnius import JavaException, JavaClass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
________________________________________ ERROR collecting tests/test_basics.py _________________________________________
test_basics.py:6: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_______________________________________ ERROR collecting tests/test_bytearray.py _______________________________________
test_bytearray.py:5: in <module>
    from jnius import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_________________________________________ ERROR collecting tests/test_cast.py __________________________________________
test_cast.py:5: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
___________________________________ ERROR collecting tests/test_chars_and_strings.py ___________________________________
test_chars_and_strings.py:7: in <module>
    from jnius.reflect import autoclass, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
____________________________________ ERROR collecting tests/test_class_argument.py _____________________________________
test_class_argument.py:5: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_______________________________________ ERROR collecting tests/test_closeable.py _______________________________________
test_closeable.py:7: in <module>
    from jnius import autoclass, JavaException, protocol_map
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_collections.py ______________________________________
test_collections.py:3: in <module>
    from jnius import autoclass, protocol_map
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_comparable.py _______________________________________
test_comparable.py:3: in <module>
    from jnius import autoclass, protocol_map
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_constructor.py ______________________________________
test_constructor.py:7: in <module>
    from jnius import autoclass, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
__________________________________________ ERROR collecting tests/test_dir.py __________________________________________
test_dir.py:5: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_________________________________________ ERROR collecting tests/test_enum.py __________________________________________
test_enum.py:19: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_____________________________________ ERROR collecting tests/test_export_class.py ______________________________________
test_export_class.py:5: in <module>
    from jnius import autoclass, java_method, PythonJavaClass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
____________________________________ ERROR collecting tests/test_implementation.py _____________________________________
test_implementation.py:7: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_int_vs_long.py ______________________________________
test_int_vs_long.py:3: in <module>
    from jnius import autoclass, cast, PythonJavaClass, java_method
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_______________________________________ ERROR collecting tests/test_interface.py _______________________________________
test_interface.py:6: in <module>
    from jnius import autoclass, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________ ERROR collecting tests/test_method_multiple_signatures.py _______________________________
test_method_multiple_signatures.py:6: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
____________________________________ ERROR collecting tests/test_multidimension.py _____________________________________
test_multidimension.py:5: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_object_args.py ______________________________________
test_object_args.py:11: in <module>
    from jnius import autoclass, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________________ ERROR collecting tests/test_output_args.py ______________________________________
test_output_args.py:5: in <module>
    from jnius import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________ ERROR collecting tests/test_pass_by_reference_or_value.py _______________________________
test_pass_by_reference_or_value.py:5: in <module>
    from jnius import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_________________________________________ ERROR collecting tests/test_proxy.py _________________________________________
test_proxy.py:7: in <module>
    from jnius import autoclass, java_method, PythonJavaClass, cast
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
________________________________________ ERROR collecting tests/test_reflect.py ________________________________________
test_reflect.py:5: in <module>
    from jnius.reflect import autoclass
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_______________________________________ ERROR collecting tests/test_signature.py _______________________________________
test_signature.py:3: in <module>
    from jnius import autoclass, java_method, PythonJavaClass, cast
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
________________________________________ ERROR collecting tests/test_simple.py _________________________________________
test_simple.py:5: in <module>
    from jnius import JavaClass, MetaJavaClass, JavaMethod
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
________________________________________ ERROR collecting tests/test_static.py _________________________________________
test_static.py:7: in <module>
    from jnius import autoclass, JavaException, JavaMethod, JavaMultipleMethod
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
____________________________________ ERROR collecting tests/test_visibility_all.py _____________________________________
test_visibility_all.py:7: in <module>
    from jnius import JavaMultipleMethod, JavaMethod
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
_____________________________ ERROR collecting tests/test_visibility_package_protected.py ______________________________
test_visibility_package_protected.py:7: in <module>
    from jnius import JavaMethod, JavaStaticMethod, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
________________________________ ERROR collecting tests/test_visibility_public_only.py _________________________________
test_visibility_public_only.py:7: in <module>
    from jnius import JavaMethod, JavaStaticMethod, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
______________________________ ERROR collecting tests/test_visibility_public_protected.py ______________________________
test_visibility_public_protected.py:7: in <module>
    from jnius import JavaMultipleMethod, JavaException
../jnius/__init__.py:42: in <module>
    from .reflect import *  # noqa
../jnius/reflect.py:20: in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
/usr/local/lib/python2.7/dist-packages/six.py:856: in __new__
    return meta(name, resolved_bases, d)
jnius/jnius_export_class.pxi:119: in jnius.MetaJavaClass.__new__
    ???
jnius/jnius_export_class.pxi:179: in jnius.MetaJavaClass.resolve_class
    ???
jnius/jnius_env.pxi:11: in jnius.get_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:134: in jnius.get_platform_jnienv
    ???
jnius/jnius_jvm_dlopen.pxi:87: in jnius.create_jnienv
    ???
E   TypeError: Error when calling the metaclass bases
E       Expected unicode, got str
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 32 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 32 error in 1.91 seconds ===============================================
make: *** [Makefile:28: tests] Error 2

**Comment by AndiEcker** [comment]
use version 3+ of Python  (instead of 2.7)

Am Do., 28. Jan. 2021 um 03:20 Uhr schrieb yhryyq <notifications@github.com

**Comment by misl6** [comment]
Closing as the issue refers on a old version of `pyjnius`, and we do not support Python **2.7** anymore.
Feel free to re-open the issue if it persists on a recent `pyjnius` version (on a supported Python 3 version)
