### ISSUE TITLE
How to use FingerPrint Manager using Pyjnius in kivy?

### ISSUE THREAD

**Issue by AM-ash-OR-AM-I** [kivy/pyjnius#580]
I wanted to use biometric authentication using https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager can anyone give me code/idea of how to do it exactly in pyjnius in kivy?

**Comment by Huxtech** [comment]
Clone my repo and make necessary adjustments

https://github.com/Huxtech/Android-Biometrics
