### ISSUE TITLE
system error of jnius running together with pyimagej

### ISSUE THREAD

**Issue by physlly** [kivy/pyjnius#581]
I would like to run fiji plugin/macro in python (with pyimage). I am following the tutorial as follows. https://nbviewer.jupyter.org/github/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb

***
To run the plugin, it requires autoclass from jnius. However, "systemerror : JVM5 failed to start" pops up after "imagej.init()".  If I run jnius before imagej.init(), then the error will be in imagej side.  Please see below for the screenshot of the error. Any advise  ?? Thank you very much !!

<img width="880" alt="Screenshot 2021-01-27 at 08 38 48" src="https://user-images.githubusercontent.com/75789762/106414550-23c05a00-644d-11eb-99de-2df549679805.png">

**Comment by hx2A** [comment]
I'm not familiar with [PyImageJ](https://github.com/imagej/pyimagej), but from what I gather in their documentation and their code, it seems to use the [jpype](https://github.com/jpype-project/jpype) library to connect Python to a Java library called ImageJ. Jpype is a different Java-Python bridge that does similar things as pyjnius. Both connect to a JVM, but that doesn't mean they can inter-operate. If you want to use PyImageJ, I think you will be better off using jpype to do what you are doing and not pyjnius.

Good luck!
