### ISSUE TITLE
Missing Files After Installation of pyjnius 1.3.0

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [kivy/pyjnius#583]
Dear All 
I have installed pyjnius in UbuntuApp in Windows 10 + Python 3.9 and latest pip 21

The problem is that after the successfult installation of the latest  pyjnius 1.3.0 >>> There are many missing files not same as your files in repository >> This is resultant jnius folder after installation and I have only pyjnius distribution folder 

![image](https://user-images.githubusercontent.com/47518534/108623453-1a685300-7437-11eb-9233-b93b404e5d66.png)

Jnius Folder 

![image](https://user-images.githubusercontent.com/47518534/108623523-5b606780-7437-11eb-9f6b-adbb0a8788a0.png)

The File "jnius_jvm_dlopen.pxi" is not Found

![image](https://user-images.githubusercontent.com/47518534/108623603-b3976980-7437-11eb-8b53-9ea9a8027988.png)

I downloaded the missing files from here and paste them in my jnius library 
![image](https://user-images.githubusercontent.com/47518534/108625604-bb5d0b00-7443-11eb-8ffa-11b5ad340323.png)

I mapped to the location of the file >>> The error still arising 
![image](https://user-images.githubusercontent.com/47518534/108625680-17279400-7444-11eb-9ba2-91c076f44f89.png)

**Comment by cmacdonald** [comment]
.pxi files are compiled into the binary. I think your problem is your classpath is incomplete, as suggested by the NoClassDefFoundError

**Comment by ABDULAZIZALQATAN** [comment]
Thank you sir 
First of all , sorry for not replying because I was sick and too busy finding solutions for this 
you are right >>> The Pxi files were not recognized inside Ubuntu after manual copy >>> So , I copied another version in Desktop and detect them from Ubuntu 
The problem Now how to define the classes of Lucene in Pyjnius 

![image](https://user-images.githubusercontent.com/47518534/109391618-e944c280-790f-11eb-9e34-a649abf45165.png)

**Comment by cmacdonald** [comment]
Copying files manually to the desktop etc is not the way to install Pyjnius. 

As you have a Pyserini problem, I think you should ask the Pyserini folk for help.  Alternatively, nearer to home, may I suggest PyTerrier?
