### ISSUE TITLE
Core dump produced by my application

### ISSUE THREAD

**Issue by inventzia** [kivy/pyjnius#585]
Hello, first of all thanks for the great library! I have been joyfully using it happily for several months now in simple applications.

 Lately I am incurring an issue, which is not totally reproducible in the sense that I am unable to produce a test case that always crashes. I have set it to produce a core dump, and obtained one, opened it with gdb then looked at the stack trace via bt. And this is where I cannot really tell at all what is going on. There is jnius in the stack and calls to Java from python so I thought if I shared the stack trace with you maybe I'll find someone nice that is able to point me in the right direction to what is going on. File attached. 
[gdb-bt-output.txt](https://github.com/kivy/pyjnius/files/6165448/gdb-bt-output.txt)

**Comment by cmacdonald** [comment]
Hi @inventzia

Your stack trace doesnt really show the Java stack trace, which can be important for debugging things. I find that the hs_err_pid log file generated from a JVM crash to be more informative.

In general, I have found when using Jnius that problems in the JVM arise from:
(a) passing the wrong type to a function
(b) passing an object that then goes out of scope in Python, causing it to be GCd while the equivalent Java object still exists. Often crashed can be avoided by holding a Python reference to an object for as long as it is needed inside any Java code.

**Comment by inventzia** [comment]
hello @cmacdonald thanks for the suggestion, especially point b) which I was not aware of. Basically you are saying that java objects created from Python and passed to another component (for example a java thread that will use and hold onto them) when going out of scope in the Python module that created them are GCd regardless of the fact that another thread is still using them?

**Comment by cmacdonald** [comment]
Yes. The Python GC doesnt count Java references. 

AIUI, passing a "Python Java object" (which cannot be converted, like int or String) to Java causes a Java proxy to be created. Any method invoked on the proxy is then passed back to Python. So the pointer to the Python implementation still has to be valid.

**Comment by inventzia** [comment]
Thanks for the suggestions
