### ISSUE TITLE
Callback is not working

### ISSUE THREAD

**Issue by jain18aditya** [kivy/pyjnius#586]
I am trying to implement callback from Java to python using pyjnius

My Code:
TestClass.py
```
            dataStoreClientPackage  = autoclass('com.test.TestClient')
            handle = testClientPackage(Context)
            print(handle)

            serviceConnection = Service_Connection_Callback()
            handle.connect(Constants.DATA_DIR, Constants.namespace, serviceConnection, None)

```

ServiceConnectionCallback.py

```
from jnius import PythonJavaClass, java_method

class Service_Connection_Callback(PythonJavaClass):
    __javainterfaces__ = ['test/callback/ServiceConnectionCallback']

    actualResult = ""
    @java_method('()Z')
    def onConnect(self) :
        print ("Connected")

    @java_method('()Ljava/lang/Object;')
    def onFailure(self, err) :
        print("Failed to connect with error "+ err)
```

While running i am getting below error:
```
Test/ds_init/TestInit.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
jnius/jnius_export_class.pxi:857: in jnius.JavaMethod.__call__
    ???
jnius/jnius_export_class.pxi:954: in jnius.JavaMethod.call_method
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   jnius.JavaException: JVM exception occurred: Stub! java.lang.RuntimeException

jnius/jnius_jvm_dlopen.pxi:91: JavaException
```

I believe this is in callback but not able to RC or fix this?

**Comment by hx2A** [comment]
I think we will need to see more of your code to help here. The `serviceConnection` is being passed to `handle.connect`, but what does that `connect` method do? What calls does it make to `serviceConnection`? Also, where is the Java code for 'test/callback/ServiceConnectionCallback'? Is that an Interface?

**Comment by jain18aditya** [comment]
connect method connects to a system service which accepts above 4 params,  `handle.connect(Constants.DATA_DIR, Constants.namespace, serviceConnection, None)`
First is path, second is db name, 3rd is Service Connection callback and 4th is listner but it accepts none as well.

test/callback/ServiceConnectionCallback'?
Yes this is an interface

Code:

```
public interface ServiceConnectionCallback {
    void onConnect();
    void onFailure(String errorMessage);
}

```

**Comment by hx2A** [comment]
I see your signature for `onFailure` is different. Your Java code has it with a String parameter and returning void, but in Python it has no parameters and returns an object.

**Comment by jain18aditya** [comment]
Are you pointing out here:

`    __javainterfaces__ = ['test/callback/ServiceConnectionCallback']

    actualResult = ""
    @java_method('()Z')
    def onConnect(self) :
        print ("Connected")

    @java_method('()Ljava/lang/Object;')
    def onFailure(self, err) :
        print("Failed to connect with error "+ err)`

What is it supposed to be in that case. My java coed is correct and.i want to implement same in Python

**Comment by jain18aditya** [comment]
I have added logs in callback class before any method and it is not reaching to that point either, So i believe this error is not related to the error i am getting.
