### ISSUE TITLE
Extending Java Generic Class in Python

### ISSUE THREAD

**Issue by AndreFCruz** [kivy/pyjnius#590]
I have a Java generic class of the sorts `public class Box<T> { ... }`

I need to have objects of type `Box<Square>` in Python.

I'm trying to either
1. have a python wrapper for this class that I can parameterize with the types I need (so I can get python objects of type `Box<Square>`)
2. or extend this java generic class in python, so that I can subclass it with the types I need

How would I do this? Is it even possible?

Thanks

**Comment by cmacdonald** [comment]
Currently, you cant subclass Java classes in Pyjnius.

**Comment by RobertFlatt** [comment]
You have to subclass in Java, then pass `Box<Square>` in the normal way.

If the case is a Java callback, then a wrapper is always required. 
I pointed to an example here https://github.com/kivy/pyjnius/issues/592#issuecomment-855171442
