### ISSUE TITLE
 android.speech.tts.UtteranceProgressListener is not an interface

### ISSUE THREAD

**Issue by Sahil-pixel** [kivy/pyjnius#593]
i was writing code for tts 
https://developer.android.com/reference/android/speech/tts/UtteranceProgressListener
```python
class OnProgressListener(PythonJavaClass):
    __javainterfaces__ = ['android/speech/tts/UtteranceProgressListener']
    _callback=None
    def __init__(self,callback):
        super().__init__()
        self._callback=callback


    @java_method('(Ljava/lang/String;)V')
    def onStart(self,utteranceId):
        print("pykivdroid-----onStart")

    @java_method('(Ljava/lang/String;Z)V')
    def onStop(self,utteranceId,interrupted):
        print("pykivdroid-----onStop")

    @java_method('(Ljava/lang/String;III)V')
    def onRangeStart(self, utteranceId,  start,  end,  frame):
        print("pykivdroid-----onRANGESTART")




class TTS():
    def __init__(self,**kwargs):

        

        self._tts=TextToSpeech(mActivity,None)
        if sdk_int>=15:
            obj=OnProgressListener(None)
            self._tts.setOnUtteranceProgressListener(obj)

```

runtime log in android 8
  File "jnius/jnius_export_class.pxi", line 768, in jnius.jnius.JavaMethod.__call__
06-04 12:41:31.936 14401 14467 I python  :    File "jnius/jnius_export_class.pxi", line 934, in jnius.jnius.JavaMethod.call_staticmethod
06-04 12:41:31.937 14401 14467 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
06-04 12:41:31.939 14401 14467 I python  :  jnius.jnius.JavaException: JVM exception occurred: android.speech.tts.UtteranceProgressListener is not an interface
06-04 12:41:31.939 14401 14467 I python  : Python for android ended.

**Comment by RobertFlatt** [comment]
> public abstract class UtteranceProgressListener 

It is declared as an abstract class. Pyjnius has to have an implementation to import. 

https://github.com/RobertFlatt/Android-for-Python/tree/main/Android-for-Python-Users#pyjnius  para 4

**Comment by Sahil-pixel** [comment]
Ok that means I have to write code in java ?But I want to pass some python callback function when ... in  onRangeStart() .is it possible 
...

**Comment by RobertFlatt** [comment]
Python code implementing a Java callback?
Yes - there is an example in cameraxf.
I highlighted some part here https://github.com/kivy/pyjnius/issues/592#issuecomment-855171442
