### ISSUE TITLE
jnius masks KeyboardInterrupt

### ISSUE THREAD

**Issue by notEvil** [kivy/pyjnius#596]
Hi,

when I run  `python -c "import jnius; import time; print('here'); time.sleep(100)"`  and interrupt it with Ctrl-C it doesn't raise the usual KeyboardInterrupt exception. Can you reproduce this, and is this intendend?

**Comment by cmacdonald** [comment]
Java installs it own signal handlers. Can you try removing the signal handlers?

```python
import jnius_config
jnius_config.add_options('-Xrs)
```

**Comment by notEvil** [comment]
Thats it, thanks! Maybe this should be set by default and `System.exit()` (from java man page) registered with `atexit`?

**Comment by cmacdonald** [comment]
I think there might be negative speed implications...
I will test here and see the impact on my use case.

**Comment by notEvil** [comment]
Just read in the docs that `atexit` won't work here, forget my suggestion

**Comment by cmacdonald** [comment]
> Just read in the docs that atexit won't work here, forget my suggestion

Whats the reason?

**Comment by notEvil** [comment]
Its noted at the very top of https://docs.python.org/3/library/atexit.html. In short `atexit` doesn't trigger on SIGHUP and SIGTERM (but does on SIGINT)

**Comment by Julian-O** [comment]
I interpret this as resolved. If that is wrong, please let us know.
