### ISSUE TITLE
jnius.jnius.JavaException: Class not found

### ISSUE THREAD

**Issue by mehdializade** [kivy/pyjnius#604]
I made a test application on kivy to call a service. I have these files:
main.py

```
from kivy.app import App
from kivy.uix.button import Button
from jnius import autoclass


class TestButton(Button): 
    # When the button is pressed, this function is called
    def run_test_service(self):
        service = autoclass('org.test.myapp.ServiceMyservice')
        mActivity = autoclass('org.kivy.android.PythonActivity').mActivity
        argument = ""
        service.start(mActivity, argument)


class ServiceTestApp(App):
    def build(self):
        return TestButton()


if __name__ == "__main__":
    ServiceTestApp().run()
```
buildozer.spec

```
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

...
# (list) List of service to declare
#services = Myservice:main.py
```
As a result, I get the error:

`jnius.jnius.JavaException: Class not found b'org/test/myapp/ServiceMyservice
`

What should I specify in the service argument to access the service script?

**Comment by tshirtman** [comment]
we don't usually use issues for support but you can have a look at this example https://github.com/tshirtman/kivy_service_osc i think your issue might be that your service is not your main.py, but i'm not sure.

**Comment by mehdializade** [comment]
It makes me proud that you answered. Thank you.
I used exactly the same [example](https://github.com/tshirtman/kivy_service_osc). I got the following error when I ran `buildozer android release` for this example. 
```
# ERROR: Trying to release a package that starts with org.kivy
#
# The package.domain org.kivy is reserved for the Kivy official
# applications. Please use your own domain.
#
# If you are a Kivy developer, add an export in your shell
# export BUILDOZER_ALLOW_KIVY_ORG_DOMAIN=1
```
Then I applied the following changes to fix the above error,
In Buildozer.spec:
```
# (str) Package name
package.name = oscservice

# (str) Package domain (needed for android/ios packaging)
package.domain = org.kivy
```
and in main.py: `service = autoclass('org.kivy.oscservice.ServiceMyservice')`.  but I got error `jnius.jnius.JavaException: Class not found b'org/test/myapp/ServiceMyservice`.
Thank you for your help in resolving any of the above errors so that I can get the release file.
