### ISSUE TITLE
Python 3.10 Support?

### ISSUE THREAD

**Issue by Hunter2807** [kivy/pyjnius#606]
Hey!

I am trying to use this module with Python 3.10 but getting this build error when I try to install in 3.10 --> https://paste.pythondiscord.com/eququniwaf.py

Is there any way to fix it? And are there any plans to support 3.10?

**Comment by tshirtman** [comment]
https://github.com/kivy/pyjnius/pull/607 let's see if it builds

**Comment by Hunter2807** [comment]
Ah really thanks for that! Let's see what happens...

**Comment by tshirtman** [comment]
Should be good now!
