### ISSUE TITLE
Incompatibility of zip.dll between pyjnius and libzip on Windows conda

### ISSUE THREAD

**Issue by floriandeboissieu** [kivy/pyjnius#610]
When both installed, e.g. conda create -n pyjnius pyjnius libzip, it leads to a ClobberError on "zip.dll" between openjdk and libzip, which then leads to an error at JVM initialization:
```
$ python -c "import jnius"
C:\Users\Toto\miniconda3\envs\pyjnius\Library
C:\Users\Toto\miniconda3\envs\pyjnius\Library
Error occurred during initialization of VM
Corrupted ZIP library: C:\Users\Toto\miniconda3\envs\ptdvenv4\Library\bin\zip.dll
```
An issue has been opened also on openjdk-feedstock: https://github.com/conda-forge/openjdk-feedstock/issues/86

**Comment by Julian-O** [comment]
This appears to have been solved in the linked conda-forge issue, so closing here.

If you think this is in error, please let us know.
