### ISSUE TITLE
python3 setup.py build error !

### ISSUE THREAD

**Issue by Oopas** [kivy/pyjnius#621]
Python: 3.10.4
Cython: 0.29.28
openjdk: 18
jnius: python3.10_ci
GCC reported a lot of errors when compiling jnius.c😥
This is log:
[1.log](https://anonfiles.com/J2f03dfcy6/1_log)

**Comment by cmacdonald** [comment]
Can you paste some relevant logs  here - your link takes us to a spammy website.

**Comment by Julian-O** [comment]
No response after over a year. Closing as can't repro.

If you have more information, please let us know.
