### ISSUE TITLE
How can I do The following things ??

### ISSUE THREAD

**Issue by USER4247** [kivy/pyjnius#635]
I am making an app where users can send data to each other . I wanted the app to show in android share-sheet ie when user selects something from within android system , users must have option in share sheet to send data from my app . Whenever the app will be called from share-sheet , I want to execute a method from main code to select the users who the sender wants to send data and send that data to selected users .

Also I found a code to open pdf files in native pdf viewer , But I dont Know how to implement it . I want to open pdf in another app from my app .

Thank you

**Comment by Android-for-Python** [comment]
https://github.com/Android-for-Python/share_send_example
https://github.com/Android-for-Python/share_receive_example
https://github.com/Android-for-Python/PDFview-Example
