### ISSUE TITLE
How to get camera resolutions ??

### ISSUE THREAD

**Issue by USER4247** [kivy/pyjnius#636]
I am making camera in kivy . Kivy camera requires resolution , but I want app to use max resolution supported by front or back camera .
How can I do so ?

**Comment by Android-for-Python** [comment]
An answer to this question would be camera provider specific. And require querying the provider, Kivy Camera does not query the provider.

With some camera providers an app can query and specify resolutions, with some it can't.
Kivy Camera, mostly but not always, uses the minimum resolution. 

https://github.com/Android-for-Python/Camera4Kivy  generally (but not always) uses the max resolution provided by the camera provider. Though the camera provider default aspect ratio is a constraint.

Resolution can be viewed in a few different contexts https://github.com/Android-for-Python/Camera4Kivy#resolution
