### ISSUE TITLE
Unable to Import Pyjnius With Reticulate in R

### ISSUE THREAD

**Issue by compbiolover** [kivy/pyjnius#637]
Hi,
I am currently using a machine reading program (`INDRA`) that relies on `pyjnius` for offline reading of papers. I am using it from `R` through the `reticulate` (https://github.com/rstudio/reticulate) package that is referencing a python binary in a `miniconda` (https://docs.conda.io/en/latest/miniconda.html) environment. I believe this is causing problems with `pyjnius` as I am unable to import it. It keeps giving me a `key_error` about `JAVA_HOME`. I have repeatedly tried to set `JAVA_HOME` as both my system-wide jdk instillation and my virtual environment jdk and nothing changes.  I was hoping someone could point me towards a way to point me to setting up `pyjnius` to access the `JDK` that is installed in my `miniconda` environment.

-Andrew

**Comment by cmacdonald** [comment]
Can you add the location of jdk/bin to the PATH env var? I think jnius searches the PATH as well.

**Comment by tshirtman** [comment]
can you show the env that you see from R? can you use reticulate to import a simple python module that shows the env seen from there?

```py
from os import environ
print("\n".join(f"{k}: {v}" for k, v in environ.items()))
```
and check if `JAVA_HOME` is in there?

(of course, feel free to remove sensitive information if you post it there).

**Comment by compbiolover** [comment]
Hi @tshirtman & @cmacdonald,
Thanks for your quick responses. I ran the command and don't see `Java_HOME` at all in the env. How can I add it? I tried what was recommended here (https://indra.readthedocs.io/en/latest/installation.html#installing-indra) but that doesn't appear to have worked when I used the location of the openJDK installed in `miniconda`. The location of openJDK is `/Users/myuser/opt/miniconda3/envs/indra/bin/`

**Comment by tshirtman** [comment]
You could set that env variable from code, either from R or python (updating the "environ" dict) depending on what you prefer, and se if that helps.

**Comment by compbiolover** [comment]
Okay, I was able to add it and it says it is in there, but it now it throws the following error: ```SystemError: Error calling dlopen(b'/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/server/libjvm.dylib': b'dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/server/libjvm.dylib, 10): image not found'``` when I try to import `jnius`. Maybe I don't have my jar set up correctly?

**Comment by compbiolover** [comment]
Hi @tshirtman,
I got this figured out. I have to reference the version of the `jdk` that is outside my `miniconda` environment in combination with adding `JAVA_HOME` to the `.Renviron` file. Thanks for all your help.
