### ISSUE TITLE
Exception: Unable to create jni env, no jvm dll found.

### ISSUE THREAD

**Issue by Adlemex** [kivy/pyjnius#646]
I added the jre server folder to the path and installed java home
jvm.dll in place
but i get error:
```
Traceback (most recent call last):
  File "D:\Unity\DiaryBackend\main.py", line 20, in <module>
    import jnius
  File "D:\Unity\DiaryBackend\venv\lib\site-packages\jnius\__init__.py", line 42, in <module>
    raise Exception("Unable to create jni env, no jvm dll found.")
Exception: Unable to create jni env, no jvm dll found.
```
i installed the library for python 3.9 using wheels, amd64

my code:
```
import jnius 
test = jnius.autoclass('x2.X')
```

**Comment by yi-you** [comment]
PyJNIus depends on [Cython](http://cython.org/) and the [Java](http://www.oracle.com/javase) Development Kit (includes the Java Runtime Environment).
[https://pyjnius.readthedocs.io/en/stable/installation.html#installation-for-windows
](url)

**Comment by misl6** [comment]
> I added the jre server folder to the path and installed java home jvm.dll 

Can you please share some more details about your setup?
Also, did you followed the instructions posted by @yi-you ?

**Comment by Julian-O** [comment]
No response. Closing as Can't Repro.

If you have more info, let us know.
