### ISSUE TITLE
from .jnius import * --> No module named jnius

### ISSUE THREAD

**Issue by cwchentw** [kivy/pyjnius#65]
I compile jnius on MS Win 8 ( 64ibt ).  The Python ver. is 2.7 ( 32bit ).  The Oracle Java JDK ver. is 1.7.0_25 ( 32bit )  The C/C++ compiler was TDM-GCC 4.7 ( 32bit )
After some hack,  I finish the compile process and install the egg
If I kept the jnius.pyd as original name, the Python intepreter complain no dll loaded
If I rename the jnius.pyd to jnius.dll, the Python interpreter complained No module named jnius.
##

**Comment by andong777** [comment]
I also got the error while installing it on mac...

**Comment by hamid1380** [comment]
I also got this error while installing it on windows 8.1 64 bit

**Comment by KeyWeeUsr** [comment]
This is mainly Windows issue with `jvm.dll`, however if you've installed on Mac, make sure you have that `jre/bin/server` on your path, otherwise it won't work.
