### ISSUE TITLE
Issue when calling androidx.biometric AuthenticationCallback

### ISSUE THREAD

**Issue by YippeyKiA** [kivy/pyjnius#652]
Issue seems to occur when calling the AuthenticationCallback portion of androidx.biometrics, This class is called later when creating a biometricPrompt but as shown there seems to be a visibility error. This snippet is part of a Python, Kivy, Buildozer, Android project so will share what is relevant. Many thanks in advance

Buildozer:
android.gradle_dependencies = com.google.android.material:material:1.4.0, androidx.biometric:biometric:1.2.0-alpha05, com.android.support:appcompat-v7:28.0.0

build.gradle:
dependencies {
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.biometric:biometric:1.2.0-alpha05'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    

Logs:
05-03 18:24:27.098   503  1234 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
05-03 18:24:27.098   503  1234 I python  :  jnius.jnius.JavaException: JVM exception occurred: class androidx.biometric.BiometricPrompt$AuthenticationCallback is not visible from class loader java.lang.IllegalArgumentException

Code:
from jnius import autoclass, cast, PythonJavaClass, java_method
class AuthenticationCallback(PythonJavaClass):
    __javainterfaces__ = ['androidx/biometric/BiometricPrompt$AuthenticationCallback']

    def __init__(self, success, error):
        super(AuthenticationCallback, self).__init__()
        self.success = success
        self.error = error

    @java_method('(Landroidx/biometric/BiometricPrompt$AuthenticationResult;)V')
    def onAuthenticationSucceeded(self, result):
        self.success(result)

    @java_method('(I)V')
    def onAuthenticationError(self, errorCode):
        self.error(errorCode)

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#calling-python-from-java

For example https://github.com/Android-for-Python/speech_recognizer_example
