### ISSUE TITLE
Support for arm64(M1 Chip) arch in MACHINE2CPU

### ISSUE THREAD

**Issue by gmarupilla** [kivy/pyjnius#661]
I'm using a Python liquibase package which has a dependency on pyjnius. I was getting a SystemError when attempting to check the details of [cpu](https://github.com/kivy/pyjnius/blob/7da449434e9b1c825c283e4a9103db27d17aee2f/jnius/env.py#L369). Have you had the [opportunity to provide support](https://github.com/terrier-org/terrier-core/issues/217#issuecomment-1437542346) for Mac silicon?

_**Error Trace:**_
```
SystemError: Error calling dlopen(b'/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib'): b"dlopen(/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib' (no such file), '/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))"
```

I tried the approach from [here](https://github.com/memiiso/pyliquibase/issues/44#issuecomment-1584495601), and seems not working(as it is trying to load Java from Python).

 #_**Environment:**_

Python Verison: 3.8.17
pyjnius Version: 1.5.0
platform.machine() = arm64
Mac OS: Ventura - Apple M1 Pro Chip

_**Linked issues:**_
1. https://github.com/memiiso/pyliquibase/issues/44
2. https://github.com/kivy/pyjnius/issues/609
3. https://github.com/terrier-org/terrier-core/issues/217

**Comment by cmacdonald** [comment]
It should be possible by installing a JDK for Arm architecture, right?

Craig
