### ISSUE TITLE
How to add everything under M2 repository to pyjnius classpath?

### ISSUE THREAD

**Issue by siddhsql** [kivy/pyjnius#668]
How can I add everything under M2 respository `~/.m2/repository` to the pyjnius classpath? thanks.

**Comment by cmacdonald** [comment]
I wouldnt suggest that as a solution, as M2 can grow to large. Thats not how Maven works either.

See https://github.com/terrier-org/pyterrier/blob/master/pyterrier/mavenresolver.py for something that imports jar files from ~/.m2/

You can then add the identified jar files to the classpath:
https://github.com/terrier-org/pyterrier/blob/master/pyterrier/__init__.py#L121-L122
