### ISSUE TITLE
Moderinze `java` code?

### ISSUE THREAD

**Issue by baseplate-admin** [kivy/pyjnius#690]
https://github.com/kivy/pyjnius/blob/c144e968cdfafd58599cf697e2be63d959c6aa26/jnius/src/org/jnius/NativeInvocationHandler.java#L15-L22

Maybe with something like

```java
            String message = "+ java:invoke(<proxy>," + method + ", " + args + ")"
            System.out.print(message);
            System.out.println(")");
```

**Comment by Julian-O** [comment]
Would you care to submit a PR with the change?

**Comment by baseplate-admin** [comment]
@Julian-O, thank you for your recent work in kivy ( i really appreciate the efforts you put into the toolchains recently )

---
>Would you care to submit a PR with the change?

I will gladly do it :)
