### ISSUE TITLE
installation documentation could be refreshed

### ISSUE THREAD

**Issue by cmacdonald** [kivy/pyjnius#695]
https://pyjnius.readthedocs.io/en/latest/installation.html talks a lot about installing Cython etc, which isnt really necessary. You can pip install the binaries. That content should move to a building page, and make the installation much easier.

**Comment by cmacdonald** [comment]
Seems reasonable.

Was wondering about separating installation to another page tbh, but if it's clear that it's not normally needed, then it's already an improvement.

**Comment by misl6** [comment]
Fixed via #700
