### ISSUE TITLE
libjvm.so cannot open shared object file: Not a directory

### ISSUE THREAD

**Issue by 9acca9** [kivy/pyjnius#734]
hi
im getting this error while running a kivy app.
Running in a ubuntu 22.04.

Thanks
```
 Traceback (most recent call last):
   File "/home/panchines/Documents/main.py", line 24, in <module>
     from jnius import autoclass
   File "/home/panchines/.local/lib/python3.10/site-packages/jnius/__init__.py", line 13, in <module>
     from .reflect import *  # noqa
   File "/home/panchines/.local/lib/python3.10/site-packages/jnius/reflect.py", line 14, in <module>
     class Class(with_metaclass(MetaJavaClass, JavaClass)):
   File "/usr/lib/python3/dist-packages/six.py", line 872, in __new__
     return meta(name, resolved_bases, d)
   File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
   File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
   File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
   File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
 SystemError: Error calling dlopen(b'/usr/lib/jvm/java-17-openjdk-amd64/bin/java/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/java-17-openjdk-amd64/bin/java/jre/lib/amd64/server/libjvm.so: cannot open shared object file: Not a directory'


```
```
locate libjvm.so
/usr/lib/jvm/java-17-openjdk-amd64/lib/server/libjvm.so
/usr/share/gdb/auto-load/usr/lib/jvm/java-17-openjdk-amd64/jre/lib/server/libjvm.so-gdb.py
```

it is in a different place. I dont know how change that.
thanks
EDIT: This seems related. 
https://github.com/kivy/pyjnius/issues/209
https://github.com/kivy/pyjnius/issues/428

**Comment by 9acca9** [comment]
So, nobody else is having this error?
Can you share where you have installed this?
Im using a VM, so i can change to what works better or avoid "problems" with installation.

Thanks!

**Comment by cmacdonald** [comment]
what was the solution?

**Comment by 9acca9** [comment]
... i dont know, lol.
I keep trying things here and there... and fix it... some how... but, because i still can get the example kivy app to work, i delete everything at one point and... im getting the same error again, but... this time i dont get the solution... and i cant recall.
Because nobody here is answering im asking now here https://stackoverflow.com/questions/79064164/why-im-having-this-error-bleak-develop-branch
...still i dont have a response (but i create just yesterday, i have hope)

But, now im thinking that the example kivy app must have something that i dont noticed. Because yesterday i start from 0 making just an app for android without gui, i mean something that just run with bleak in the terminal of android... and it is working. So, im gonna contruct my app from that.
If im not doing nothing wrong i believe that the example app have something wrong and it will be good if somebody take care of that or just delete that, because beginners like i start with the "easy" way, and it seems im having more successes building "from scratch" with bleak.

**Comment by 9acca9** [comment]
sorry i response another question. About this..... i cant recall. Sorry

**Comment by cmacdonald** [comment]
For Kivy-related questions try the kivy repo. Jnius is more general than kivy.
