### ISSUE TITLE
jnius.jnius.JavaException: No methods matching your arguments

### ISSUE THREAD

**Issue by paulocheque** [kivy/pyjnius#76]
In a jnius.jnius.JavaMultipleMethod call.

I would like to check all my available options to see which parameters PyJNIus is recognizing. It there a debug command for this?

I am asking this because I am using autoclass and the parameter I am passing matchs my Java class definition, so I need more information to realize what is going on.
##

**Comment by KeyWeeUsr** [comment]
Check https://pyjnius.readthedocs.io/en/latest/api.html?highlight=javap#jnius.JavaMethod.__init__ which contains the command `javap` for signatures:

    javap -s package.file.class
