### ISSUE TITLE
Better "No methods matching your arguments" explanation

### ISSUE THREAD

**Issue by knappador** [kivy/pyjnius#80]
If at all possible, it would be wonderful to be notified what Methods matched the name, what their signatures are, and what the signature that was attempted is.  Would make correcting calls much faster.

Crappy example:

```
Tried ((('V')'Ljava/lang/String;'))
Found ((('V')'Ljava/lang/CharacterBuffer;'))
```
##

**Comment by KeyWeeUsr** [comment]
Closed by #393.
Ref #281.
