### ISSUE TITLE
python printing a unicode string into logcat/catlog

### ISSUE THREAD

**Issue by eulerreich** [kivy/pyjnius#98]
As qua-non has mentioned in the chat, printing a unicode string segfaults without any error output whatsoever. 

I can confirm I'm encountering the same thing.

One can circumvent it with a `try/except UnicodeError`, or a `u'myunicodestr'.decode('ascii', 'ignore')`, so it's a small issue. Though hopefully it gets resolved in the future.
##

**Comment by KeyWeeUsr** [comment]
Can't really reproduce, perhaps it's just Python 2 issue or maybe even something from us. Please try again with master (or at least the latest stable) that already has #285 merged, it might fix your issue.
